# Generated by Django 4.2.7 on 2025-12-06 19:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0021_crossref_and_topics_enriched"),
    ]

    operations = [
        migrations.CreateModel(
            name="Confession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_pt", models.CharField(max_length=200)),
                ("name_original", models.CharField(blank=True, help_text="Original language name", max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                (
                    "confession_type",
                    models.CharField(
                        choices=[
                            ("creed", "Creed (Short, Ecumenical)"),
                            ("confession", "Confession (Long, Denominational)"),
                            ("catechism", "Catechism (Q&A Format)"),
                            ("articles", "Articles of Faith"),
                            ("canons", "Canons/Decrees"),
                        ],
                        default="confession",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, help_text="Year written/adopted", null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Where it was written (e.g., 'Westminster, England')", max_length=200
                    ),
                ),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Authors or assembly",
                        size=None,
                    ),
                ),
                ("historical_context", models.TextField(blank=True, help_text="Why this confession was written")),
                ("full_text_en", models.TextField(blank=True, help_text="Complete text in English")),
                ("full_text_pt", models.TextField(blank=True)),
                ("full_text_original", models.TextField(blank=True, help_text="Original language text")),
                (
                    "original_language",
                    models.CharField(blank=True, help_text="Original language code (en, la, de, etc.)", max_length=20),
                ),
                (
                    "ecumenical_status",
                    models.CharField(
                        choices=[
                            ("ecumenical", "Ecumenical (All Christians)"),
                            ("protestant", "Protestant"),
                            ("reformed", "Reformed"),
                            ("lutheran", "Lutheran"),
                            ("anglican", "Anglican"),
                            ("baptist", "Baptist"),
                            ("catholic", "Catholic"),
                            ("orthodox", "Orthodox"),
                            ("other", "Other"),
                        ],
                        default="protestant",
                        max_length=20,
                    ),
                ),
                (
                    "adopted_by",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Denominations that officially adopt this confession",
                        size=None,
                    ),
                ),
                ("study_value", models.PositiveIntegerField(default=50)),
                ("difficulty_level", models.PositiveIntegerField(default=50)),
                ("wikipedia_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True, help_text="Link to authoritative source")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Confession",
                "verbose_name_plural": "Confessions",
                "db_table": "confession",
                "ordering": ["year", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="TheologicalDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("theology_proper", "Theology Proper (God)"),
                            ("christology", "Christology (Christ)"),
                            ("pneumatology", "Pneumatology (Holy Spirit)"),
                            ("anthropology", "Anthropology (Humanity)"),
                            ("hamartiology", "Hamartiology (Sin)"),
                            ("soteriology", "Soteriology (Salvation)"),
                            ("ecclesiology", "Ecclesiology (Church)"),
                            ("eschatology", "Eschatology (End Times)"),
                            ("bibliology", "Bibliology (Scripture)"),
                            ("angelology", "Angelology (Angels/Demons)"),
                            ("ethics", "Ethics & Morality"),
                            ("worship", "Worship & Liturgy"),
                        ],
                        help_text="Unique identifier for this domain",
                        unique=True,
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_pt", models.CharField(max_length=100)),
                (
                    "name_original",
                    models.CharField(blank=True, help_text="Latin/Greek term (e.g., 'Soteriologia')", max_length=100),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                (
                    "central_question_en",
                    models.CharField(blank=True, help_text="E.g., 'Who is God?' for Theology Proper", max_length=200),
                ),
                ("central_question_pt", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(blank=True, help_text="Emoji or icon name (e.g., '✝️')", max_length=50)),
                ("color", models.CharField(blank=True, help_text="Hex color for UI (e.g., '#8B0000')", max_length=20)),
                (
                    "study_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Recommended order for studying domains (1=first)"
                    ),
                ),
                ("difficulty_level", models.PositiveIntegerField(default=50, help_text="Overall difficulty (1-100)")),
                (
                    "estimated_study_hours",
                    models.PositiveIntegerField(default=10, help_text="Estimated hours to study this domain"),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_summary_pt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisite_domains",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Domains that should be studied before this one",
                        related_name="dependent_domains",
                        to="theology.theologicaldomain",
                    ),
                ),
                (
                    "related_domains",
                    models.ManyToManyField(
                        blank=True, help_text="Related domains for cross-reference", to="theology.theologicaldomain"
                    ),
                ),
            ],
            options={
                "verbose_name": "Theological Domain",
                "verbose_name_plural": "Theological Domains",
                "db_table": "theological_domain",
                "ordering": ["study_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="TheologicalPerspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_pt", models.CharField(max_length=100)),
                ("description_en", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                ("origin_year", models.CharField(blank=True, help_text="When this tradition emerged", max_length=50)),
                ("origin_location", models.CharField(blank=True, max_length=200)),
                (
                    "founder",
                    models.CharField(blank=True, help_text="Key founder (e.g., 'John Calvin')", max_length=200),
                ),
                (
                    "distinctives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Key distinctives (e.g., ['Sola Scriptura', 'TULIP'])",
                        size=None,
                    ),
                ),
                (
                    "key_figures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Important theologians in this tradition",
                        size=None,
                    ),
                ),
                (
                    "tradition_type",
                    models.CharField(
                        choices=[
                            ("catholic", "Catholic"),
                            ("orthodox", "Orthodox"),
                            ("protestant", "Protestant"),
                            ("evangelical", "Evangelical"),
                            ("other", "Other"),
                        ],
                        default="protestant",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_perspective",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent tradition (e.g., Reformed → Calvinist)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_perspectives",
                        to="theology.theologicalperspective",
                    ),
                ),
                ("related_perspectives", models.ManyToManyField(blank=True, to="theology.theologicalperspective")),
            ],
            options={
                "verbose_name": "Theological Perspective",
                "verbose_name_plural": "Theological Perspectives",
                "db_table": "theological_perspective",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Doctrine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'incarnation')", max_length=100, unique=True
                    ),
                ),
                ("name_en", models.CharField(max_length=200)),
                ("name_pt", models.CharField(max_length=200)),
                ("name_latin", models.CharField(blank=True, help_text="Latin theological term", max_length=200)),
                ("definition_en", models.TextField(help_text="One-sentence definition")),
                ("definition_pt", models.TextField(blank=True)),
                ("explanation_en", models.TextField(blank=True)),
                ("explanation_pt", models.TextField(blank=True)),
                (
                    "explanation_beginner_en",
                    models.TextField(blank=True, help_text="Simple explanation for new believers"),
                ),
                ("explanation_beginner_pt", models.TextField(blank=True)),
                (
                    "explanation_intermediate_en",
                    models.TextField(blank=True, help_text="Detailed explanation for growing Christians"),
                ),
                ("explanation_intermediate_pt", models.TextField(blank=True)),
                (
                    "explanation_advanced_en",
                    models.TextField(blank=True, help_text="Technical explanation for theology students"),
                ),
                ("explanation_advanced_pt", models.TextField(blank=True)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("essential", "Essential (Creedal)"),
                            ("important", "Important (Confessional)"),
                            ("secondary", "Secondary (Denominational)"),
                            ("tertiary", "Tertiary (Disputable)"),
                            ("speculative", "Speculative (Debated)"),
                        ],
                        default="important",
                        help_text="How essential is this doctrine?",
                        max_length=20,
                    ),
                ),
                (
                    "consensus_level",
                    models.CharField(
                        choices=[
                            ("ecumenical", "Ecumenical (All Christians)"),
                            ("orthodox", "Orthodox (Catholic/Protestant/Orthodox)"),
                            ("protestant", "Protestant Consensus"),
                            ("evangelical", "Evangelical Consensus"),
                            ("reformed", "Reformed Tradition"),
                            ("arminian", "Arminian Tradition"),
                            ("disputed", "Disputed Across Traditions"),
                        ],
                        default="evangelical",
                        help_text="Level of agreement across traditions",
                        max_length=20,
                    ),
                ),
                (
                    "anchor_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Primary Scripture proofs (e.g., ['John 1:1', 'John 1:14'])",
                        size=None,
                    ),
                ),
                (
                    "supporting_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Additional supporting verses",
                        size=None,
                    ),
                ),
                (
                    "historical_development_en",
                    models.TextField(blank=True, help_text="How this doctrine developed through church history"),
                ),
                ("historical_development_pt", models.TextField(blank=True)),
                (
                    "key_councils",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Church councils that addressed this (e.g., ['Nicaea 325'])",
                        size=None,
                    ),
                ),
                (
                    "key_figures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Key theologians (e.g., ['Athanasius', 'Augustine'])",
                        size=None,
                    ),
                ),
                (
                    "year_formulated",
                    models.CharField(blank=True, help_text="When doctrine was formally articulated", max_length=50),
                ),
                (
                    "practical_implications_en",
                    models.TextField(blank=True, help_text="How this doctrine applies to daily life"),
                ),
                ("practical_implications_pt", models.TextField(blank=True)),
                ("devotional_reflection_en", models.TextField(blank=True, help_text="Devotional/worship implications")),
                ("devotional_reflection_pt", models.TextField(blank=True)),
                (
                    "common_misunderstandings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        blank=True,
                        default=list,
                        help_text="Common errors about this doctrine",
                        size=None,
                    ),
                ),
                ("study_value", models.PositiveIntegerField(default=50, help_text="Educational value (1-100)")),
                ("difficulty_level", models.PositiveIntegerField(default=50, help_text="Complexity level (1-100)")),
                (
                    "estimated_study_time",
                    models.PositiveIntegerField(default=30, help_text="Estimated minutes to study"),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_summary_pt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("canonical", "Canonical"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrasting_doctrines",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Opposing/heretical views",
                        related_name="contrasted_by",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctrines",
                        to="theology.theologicaldomain",
                    ),
                ),
                (
                    "parent_doctrine",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent doctrine for hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_doctrines",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "prerequisite_doctrines",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Doctrines that should be understood first",
                        related_name="dependent_doctrines",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "related_doctrines",
                    models.ManyToManyField(
                        blank=True, help_text="Related doctrines", related_name="+", to="theology.doctrine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine",
                "verbose_name_plural": "Doctrines",
                "db_table": "doctrine",
                "ordering": ["domain", "importance", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ConfessionArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chapter", models.PositiveIntegerField(help_text="Chapter number")),
                (
                    "section",
                    models.PositiveIntegerField(blank=True, help_text="Section number within chapter", null=True),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(blank=True, help_text="Question number (for catechisms)", null=True),
                ),
                ("title_en", models.CharField(max_length=300)),
                ("title_pt", models.CharField(blank=True, max_length=300)),
                ("text_en", models.TextField()),
                ("text_pt", models.TextField(blank=True)),
                ("text_original", models.TextField(blank=True)),
                ("question_en", models.TextField(blank=True, help_text="Question text (for catechisms)")),
                ("question_pt", models.TextField(blank=True)),
                ("answer_en", models.TextField(blank=True, help_text="Answer text (for catechisms)")),
                ("answer_pt", models.TextField(blank=True)),
                (
                    "scripture_proofs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Scripture references cited as proofs",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="theology.confession"
                    ),
                ),
                (
                    "doctrines",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Doctrines taught in this article",
                        related_name="confession_articles",
                        to="theology.doctrine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confession Article",
                "verbose_name_plural": "Confession Articles",
                "db_table": "confession_article",
                "ordering": ["confession", "chapter", "section"],
            },
        ),
        migrations.AddField(
            model_name="confession",
            name="perspective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confessions",
                to="theology.theologicalperspective",
            ),
        ),
        migrations.CreateModel(
            name="TheologicalQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question_en", models.TextField()),
                ("question_pt", models.TextField(blank=True)),
                (
                    "alternate_phrasings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        default=list,
                        help_text="Other ways people ask this question",
                        size=None,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert/Academic"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("has_consensus", models.BooleanField(default=True, help_text="Is there consensus among Christians?")),
                (
                    "consensus_answer_en",
                    models.TextField(blank=True, help_text="The answer most Christians would agree on"),
                ),
                ("consensus_answer_pt", models.TextField(blank=True)),
                ("short_answer_en", models.CharField(blank=True, help_text="One-sentence answer", max_length=500)),
                ("short_answer_pt", models.CharField(blank=True, max_length=500)),
                (
                    "key_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                (
                    "search_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Tags for search (e.g., ['salvation', 'eternal life'])",
                        size=None,
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=0, help_text="How often this question is asked")),
                ("is_common", models.BooleanField(default=False, help_text="Is this a frequently asked question?")),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctrine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="theology.theologicaldomain",
                    ),
                ),
                ("related_questions", models.ManyToManyField(blank=True, to="theology.theologicalquestion")),
            ],
            options={
                "verbose_name": "Theological Question",
                "verbose_name_plural": "Theological Questions",
                "db_table": "theological_question",
                "ordering": ["-frequency", "question_en"],
                "indexes": [
                    models.Index(fields=["domain"], name="theological_domain__00f779_idx"),
                    models.Index(fields=["difficulty"], name="theological_difficu_1ac348_idx"),
                    models.Index(fields=["is_common"], name="theological_is_comm_5a5b91_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctrineVerseLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Proof (Direct)"),
                            ("supporting", "Supporting (Secondary)"),
                            ("illustrative", "Illustrative (Example)"),
                            ("implicit", "Implicit (Inferred)"),
                            ("typological", "Typological (Type/Shadow)"),
                            ("disputed", "Disputed (Debated)"),
                        ],
                        default="supporting",
                        max_length=20,
                    ),
                ),
                ("explanation_en", models.TextField(blank=True, help_text="How this verse supports the doctrine")),
                ("explanation_pt", models.TextField(blank=True)),
                (
                    "hermeneutical_notes",
                    models.TextField(blank=True, help_text="Notes on interpretation of this verse"),
                ),
                ("relevance", models.FloatField(default=1.0, help_text="Relevance score (0-1)")),
                (
                    "is_disputed",
                    models.BooleanField(
                        default=False, help_text="Is the use of this verse for this doctrine disputed?"
                    ),
                ),
                ("dispute_notes", models.TextField(blank=True, help_text="Notes on the dispute")),
                ("ai_analysis", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="verse_links", to="theology.doctrine"
                    ),
                ),
                (
                    "perspectives_using",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which traditions cite this verse for this doctrine",
                        related_name="doctrine_verse_usages",
                        to="theology.theologicalperspective",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="doctrine_links", to="bible.verse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine-Verse Link",
                "verbose_name_plural": "Doctrine-Verse Links",
                "db_table": "doctrine_verse_link",
                "indexes": [
                    models.Index(fields=["support_type"], name="doctrine_ve_support_32bcb2_idx"),
                    models.Index(fields=["is_disputed"], name="doctrine_ve_is_disp_c39979_idx"),
                ],
                "unique_together": {("doctrine", "verse")},
            },
        ),
        migrations.CreateModel(
            name="DoctrinePerspectiveView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_summary_en", models.TextField(help_text="Brief summary of this tradition's position")),
                ("position_summary_pt", models.TextField(blank=True)),
                (
                    "position_detailed_en",
                    models.TextField(blank=True, help_text="Detailed explanation of the position"),
                ),
                ("position_detailed_pt", models.TextField(blank=True)),
                (
                    "supporting_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Verses this tradition uses to support their view",
                        size=None,
                    ),
                ),
                (
                    "key_arguments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        default=list,
                        help_text="Main arguments for this position",
                        size=None,
                    ),
                ),
                (
                    "notable_proponents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                (
                    "argument_strength",
                    models.PositiveIntegerField(default=50, help_text="Scholarly strength of arguments (1-100)"),
                ),
                (
                    "is_official_position",
                    models.BooleanField(
                        default=True, help_text="Is this the official/majority position of this tradition?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agrees_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other perspective views that agree",
                        related_name="+",
                        to="theology.doctrineperspectiveview",
                    ),
                ),
                (
                    "disagrees_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other perspective views that disagree",
                        related_name="+",
                        to="theology.doctrineperspectiveview",
                    ),
                ),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perspective_views",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "perspective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctrine_views",
                        to="theology.theologicalperspective",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctrine Perspective View",
                "verbose_name_plural": "Doctrine Perspective Views",
                "db_table": "doctrine_perspective_view",
                "indexes": [
                    models.Index(fields=["doctrine"], name="doctrine_pe_doctrin_1faea5_idx"),
                    models.Index(fields=["perspective"], name="doctrine_pe_perspec_d76f15_idx"),
                ],
                "unique_together": {("doctrine", "perspective")},
            },
        ),
        migrations.AddIndex(
            model_name="doctrine",
            index=models.Index(fields=["domain", "importance"], name="doctrine_domain__3e2f64_idx"),
        ),
        migrations.AddIndex(
            model_name="doctrine",
            index=models.Index(fields=["consensus_level"], name="doctrine_consens_f0eb51_idx"),
        ),
        migrations.AddIndex(
            model_name="doctrine",
            index=models.Index(fields=["status"], name="doctrine_status_3bea93_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="confessionarticle",
            unique_together={("confession", "chapter", "section")},
        ),
    ]
