# Generated by Django 4.2.7 on 2026-03-30 15:56

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0022_initial_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("subtitle", models.CharField(blank=True, default="", max_length=500)),
                (
                    "study_type",
                    models.CharField(
                        choices=[
                            ("event", "Biblical Event"),
                            ("typology", "Typology / Type-Antitype"),
                            ("doctrine", "Doctrine / Theology"),
                            ("mystical", "Mystical / Contemplative"),
                            ("character", "Character Study"),
                            ("thematic", "Thematic Study"),
                            ("book", "Book Study"),
                            ("passage", "Passage / Pericope"),
                            ("devotional", "Devotional"),
                            ("freeform", "Free Form"),
                        ],
                        default="freeform",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base", "Baseline"),
                            ("medium", "Medium"),
                            ("medium_hard", "Medium-Hard"),
                            ("hard", "Hard"),
                            ("extreme", "Extreme"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public"), ("community", "Community")],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "blocks",
                    models.JSONField(
                        default=list, help_text="Ordered array of content blocks [{id, type, order, data, meta}]"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Short description for listings and previews"),
                ),
                ("cover_image_url", models.URLField(blank=True, default="")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and search",
                        size=None,
                    ),
                ),
                ("language", models.CharField(default="pt-BR", max_length=10)),
                (
                    "source_plan_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID of the study plan that originated this study",
                        max_length=100,
                    ),
                ),
                (
                    "source_validation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Original validation ID (e.g., v3_base_01) if seeded",
                        max_length=50,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("fork_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="studies", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="studies.study",
                    ),
                ),
                (
                    "source_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_studies",
                        to="bible.topic",
                    ),
                ),
            ],
            options={
                "db_table": "studies",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bookmarks", to="studies.study"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study_bookmarks",
                "unique_together": {("study", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["author", "visibility"], name="study_author_vis_idx"),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["visibility", "is_published"], name="study_vis_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(fields=["study_type"], name="study_type_idx"),
        ),
        migrations.AddIndex(
            model_name="study",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="study_tags_gin"),
        ),
    ]
