# Generated by Django 4.2.7 on 2026-03-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("entities", "0003_add_plant_ritual_literary_form_namespaces"),
        ("people", "0002_create_image_entity_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEntityLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "character_name",
                    models.CharField(help_text="Original character name from image tag", max_length=200),
                ),
                (
                    "character_type",
                    models.CharField(
                        blank=True,
                        help_text="Character type from tag: PERSON, DEITY, ANGEL, GROUP, OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("exact", "Exact match on primary_name"),
                            ("alias", "Match via EntityAlias"),
                            ("fuzzy", "Fuzzy match (SequenceMatcher)"),
                            ("tagger_index", "Match via tagger gazetteer index"),
                            ("manual", "Manual curation"),
                        ],
                        help_text="How this match was made",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, help_text="Match confidence (0.0-1.0)")),
                ("verified", models.BooleanField(default=False, help_text="Has this match been manually verified?")),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="images.biblicalimage",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image-Entity Link",
                "db_table": "image_entity_link",
                "indexes": [
                    models.Index(fields=["image"], name="image_entit_image_i_13f534_idx"),
                    models.Index(fields=["entity"], name="image_entit_entity__d25e18_idx"),
                    models.Index(fields=["person"], name="image_entit_person__ada3b8_idx"),
                    models.Index(fields=["match_method"], name="image_entit_match_m_ca91e6_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="imageentitylink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("entity__isnull", False), ("person__isnull", True)),
                    models.Q(("entity__isnull", True), ("person__isnull", False)),
                    models.Q(("entity__isnull", True), ("person__isnull", True)),
                    _connector="OR",
                ),
                name="image_entity_link_one_target",
            ),
        ),
    ]
