# Generated by Django 4.2.7 on 2025-12-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0021_crossref_and_topics_enriched"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiblicalSymbol",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "canonical_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier like 'NAT:water', 'ANM:lamb'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        choices=[
                            ("NATURAL", "Natural Elements (water, fire, wind)"),
                            ("OBJECT", "Objects (sword, crown, lamp)"),
                            ("ACTION", "Actions (washing, anointing, walking)"),
                            ("NUMBER", "Numbers (7, 12, 40)"),
                            ("COLOR", "Colors (white, red, purple)"),
                            ("DIRECTION", "Directions (east, north, up)"),
                            ("PERSON_TYPE", "Person Types (shepherd, bride, king)"),
                            ("ANIMAL", "Animals (lamb, lion, dove)"),
                            ("PLANT", "Plants (vine, olive, fig)"),
                            ("BODY", "Body Parts (hand, eye, heart)"),
                            ("COSMIC", "Cosmic (sun, moon, stars)"),
                            ("ARCHITECTURAL", "Architecture (temple, door, foundation)"),
                            ("TIME", "Time (day, night, season)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("primary_name", models.CharField(max_length=200)),
                ("primary_name_pt", models.CharField(blank=True, max_length=200)),
                (
                    "primary_name_original",
                    models.CharField(blank=True, help_text="Original Hebrew/Greek term", max_length=200),
                ),
                ("aliases", models.JSONField(blank=True, default=list, help_text="Alternative names for this symbol")),
                ("literal_meaning", models.TextField(blank=True, help_text="Physical/literal meaning of the symbol")),
                ("literal_meaning_pt", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                (
                    "associated_concepts",
                    models.JSONField(blank=True, default=list, help_text="Related theological concepts"),
                ),
                ("boost", models.FloatField(default=1.0)),
                ("priority", models.PositiveIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("canonical", "Canonical"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_enriched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated comprehensive summary of symbol usage"),
                ),
                ("ai_summary_pt", models.TextField(blank=True)),
                (
                    "ai_hermeneutical_guide",
                    models.TextField(blank=True, help_text="AI guide for interpreting this symbol"),
                ),
                ("hebrew_word", models.CharField(blank=True, max_length=100)),
                ("hebrew_transliteration", models.CharField(blank=True, max_length=100)),
                ("greek_word", models.CharField(blank=True, max_length=100)),
                ("greek_transliteration", models.CharField(blank=True, max_length=100)),
                ("strongs_hebrew", models.CharField(blank=True, max_length=20)),
                ("strongs_greek", models.CharField(blank=True, max_length=20)),
                ("study_value", models.PositiveIntegerField(default=50, help_text="Value for Bible study (1-100)")),
                (
                    "difficulty_level",
                    models.PositiveIntegerField(default=50, help_text="Complexity of interpretation (1-100)"),
                ),
                ("frequency", models.PositiveIntegerField(default=0, help_text="Number of occurrences in Scripture")),
                ("emoji", models.CharField(blank=True, help_text="Emoji representation (💧 for water)", max_length=10)),
                ("icon_name", models.CharField(blank=True, help_text="Icon library name", max_length=50)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                ("source_gazetteer", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opposite_symbol",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opposite symbol (light vs darkness)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opposite_of",
                        to="symbols.biblicalsymbol",
                    ),
                ),
                (
                    "related_symbols",
                    models.ManyToManyField(
                        blank=True, help_text="Related symbols (fire ↔ light ↔ presence)", to="symbols.biblicalsymbol"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biblical Symbol",
                "verbose_name_plural": "Biblical Symbols",
                "db_table": "biblical_symbol",
                "ordering": ["-priority", "primary_name"],
            },
        ),
        migrations.CreateModel(
            name="SymbolMeaning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meaning", models.CharField(help_text="The symbolic meaning (e.g., 'Purification')", max_length=200)),
                ("meaning_pt", models.CharField(blank=True, max_length=200)),
                ("explanation", models.TextField(blank=True, help_text="Full explanation of this meaning")),
                ("explanation_pt", models.TextField(blank=True)),
                (
                    "theological_context",
                    models.CharField(
                        choices=[
                            ("salvific", "Salvation/Redemption"),
                            ("judgment", "Judgment/Wrath"),
                            ("blessing", "Blessing/Favor"),
                            ("covenant", "Covenant"),
                            ("eschatological", "End Times"),
                            ("christological", "About Christ"),
                            ("pneumatological", "About Holy Spirit"),
                            ("ecclesiological", "About Church"),
                            ("moral", "Moral/Ethical"),
                            ("worship", "Worship/Liturgy"),
                            ("creation", "Creation"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "valence",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("ambivalent", "Context-dependent"),
                        ],
                        default="positive",
                        max_length=20,
                    ),
                ),
                (
                    "primary_reference",
                    models.CharField(blank=True, help_text="Key verse for this meaning", max_length=100),
                ),
                (
                    "supporting_references",
                    models.JSONField(blank=True, default=list, help_text="Additional supporting verses"),
                ),
                ("frequency", models.PositiveIntegerField(default=0, help_text="How often this meaning appears")),
                (
                    "is_primary_meaning",
                    models.BooleanField(default=False, help_text="Is this the most common meaning?"),
                ),
                (
                    "testament_focus",
                    models.CharField(
                        choices=[("old", "Old Testament"), ("new", "New Testament"), ("both", "Both Testaments")],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("ai_analysis", models.TextField(blank=True, help_text="AI analysis of this meaning")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="symbols.biblicalsymbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symbol Meaning",
                "verbose_name_plural": "Symbol Meanings",
                "db_table": "symbol_meaning",
                "ordering": ["symbol", "-is_primary_meaning", "-frequency"],
            },
        ),
        migrations.CreateModel(
            name="SymbolCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_pt", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="symbols.symbolcategory",
                    ),
                ),
                (
                    "symbols",
                    models.ManyToManyField(blank=True, related_name="symbol_categories", to="symbols.biblicalsymbol"),
                ),
            ],
            options={
                "verbose_name": "Symbol Category",
                "verbose_name_plural": "Symbol Categories",
                "db_table": "symbol_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SymbolProgression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage_order", models.PositiveIntegerField(help_text="Order in the progression (1=earliest)")),
                ("stage_name", models.CharField(help_text="Name of this stage (e.g., 'Paschal Lamb')", max_length=200)),
                ("stage_name_pt", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(help_text="How the symbol is understood at this stage")),
                ("description_pt", models.TextField(blank=True)),
                (
                    "biblical_era",
                    models.CharField(
                        blank=True, help_text="Era (e.g., 'Patriarchal', 'Exodus', 'Prophetic')", max_length=100
                    ),
                ),
                ("primary_book", models.CharField(blank=True, help_text="Primary book for this stage", max_length=50)),
                ("key_reference", models.CharField(blank=True, help_text="Key verse for this stage", max_length=100)),
                (
                    "theological_development",
                    models.TextField(blank=True, help_text="What new theological understanding emerged?"),
                ),
                (
                    "christological_connection",
                    models.TextField(blank=True, help_text="How does this stage point to Christ?"),
                ),
                (
                    "is_fulfilled_in_christ",
                    models.BooleanField(default=False, help_text="Is this the stage where Christ fulfills the symbol?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meaning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progression_stages",
                        to="symbols.symbolmeaning",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressions",
                        to="symbols.biblicalsymbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symbol Progression",
                "verbose_name_plural": "Symbol Progressions",
                "db_table": "symbol_progression",
                "ordering": ["symbol", "stage_order"],
                "unique_together": {("symbol", "stage_order")},
            },
        ),
        migrations.CreateModel(
            name="SymbolOccurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("literal", "Literal Usage"),
                            ("symbolic", "Symbolic/Figurative"),
                            ("both", "Both Literal and Symbolic"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="symbolic",
                        max_length=20,
                    ),
                ),
                (
                    "context_note",
                    models.TextField(blank=True, help_text="How is the symbol used in this specific context?"),
                ),
                ("context_note_pt", models.TextField(blank=True)),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("narrative", "Narrative"),
                            ("poetry", "Poetry/Wisdom"),
                            ("prophecy", "Prophecy"),
                            ("apocalyptic", "Apocalyptic"),
                            ("law", "Law"),
                            ("epistle", "Epistle"),
                            ("gospel", "Gospel"),
                            ("parable", "Parable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interpretation_certainty",
                    models.CharField(
                        choices=[
                            ("certain", "Certain"),
                            ("probable", "Probable"),
                            ("possible", "Possible"),
                            ("debated", "Debated"),
                        ],
                        default="probable",
                        max_length=20,
                    ),
                ),
                ("ai_analysis", models.TextField(blank=True, help_text="AI interpretation of symbol in this context")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meaning",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which meaning is in view in this verse?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrences",
                        to="symbols.symbolmeaning",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="symbols.biblicalsymbol",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="symbol_occurrences", to="bible.verse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Symbol Occurrence",
                "verbose_name_plural": "Symbol Occurrences",
                "db_table": "symbol_occurrence",
                "indexes": [
                    models.Index(fields=["usage_type"], name="symbol_occu_usage_t_43b2a6_idx"),
                    models.Index(fields=["genre"], name="symbol_occu_genre_0c3fb6_idx"),
                ],
                "unique_together": {("symbol", "verse")},
            },
        ),
        migrations.AddIndex(
            model_name="symbolmeaning",
            index=models.Index(fields=["theological_context"], name="symbol_mean_theolog_3b5163_idx"),
        ),
        migrations.AddIndex(
            model_name="symbolmeaning",
            index=models.Index(fields=["valence"], name="symbol_mean_valence_904f6c_idx"),
        ),
        migrations.AddIndex(
            model_name="biblicalsymbol",
            index=models.Index(fields=["namespace", "status"], name="biblical_sy_namespa_70570a_idx"),
        ),
        migrations.AddIndex(
            model_name="biblicalsymbol",
            index=models.Index(fields=["boost"], name="biblical_sy_boost_ffa405_idx"),
        ),
    ]
