# Generated by Django 4.2.7 on 2026-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("symbols", "0001_entities_and_symbols"),
    ]

    operations = [
        migrations.AddField(
            model_name="symboloccurrence",
            name="match_words",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Words in the verse text that reference this symbol (for inline highlighting)",
            ),
        ),
    ]
