# Generated by Django 4.2.7 on 2025-12-06 19:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("theology", "0001_theology_domain"),
        ("bible", "0021_crossref_and_topics_enriched"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'faith_and_obedience')", max_length=100, unique=True
                    ),
                ),
                ("name_en", models.CharField(max_length=200)),
                ("name_pt", models.CharField(blank=True, max_length=200)),
                (
                    "name_original",
                    models.CharField(blank=True, help_text="Original Hebrew/Greek term if applicable", max_length=200),
                ),
                (
                    "label_normalized",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized form for matching (e.g., 'faith_and_obedience')",
                        max_length=200,
                    ),
                ),
                ("description_short_en", models.TextField(blank=True, help_text="One-sentence description")),
                ("description_short_pt", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                (
                    "semantic_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Keywords for semantic search (e.g., ['faith', 'trust', 'belief'])",
                        size=None,
                    ),
                ),
                (
                    "anchor_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Key verses that define this theme",
                        size=None,
                    ),
                ),
                (
                    "anchor_source",
                    models.CharField(
                        choices=[
                            ("ai_trusted", "AI Trusted"),
                            ("ai_fallback", "AI Fallback"),
                            ("manual", "Manual/Curated"),
                            ("derived", "Derived from Data"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("hebrew_term", models.CharField(blank=True, max_length=100)),
                ("hebrew_transliteration", models.CharField(blank=True, max_length=100)),
                ("greek_term", models.CharField(blank=True, max_length=100)),
                ("greek_transliteration", models.CharField(blank=True, max_length=100)),
                (
                    "strongs_hebrew",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="Related Strong's Hebrew numbers",
                        size=None,
                    ),
                ),
                (
                    "strongs_greek",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        help_text="Related Strong's Greek numbers",
                        size=None,
                    ),
                ),
                ("boost", models.FloatField(default=1.0, help_text="Search ranking boost")),
                ("priority", models.PositiveIntegerField(default=50, help_text="Display priority (1-100)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("canonical", "Canonical"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("study_value", models.PositiveIntegerField(default=50, help_text="Educational value (1-100)")),
                ("difficulty_level", models.PositiveIntegerField(default=50, help_text="Complexity level (1-100)")),
                (
                    "verse_count",
                    models.PositiveIntegerField(default=0, help_text="Number of verses associated with this theme"),
                ),
                (
                    "topic_count",
                    models.PositiveIntegerField(default=0, help_text="Number of topics associated with this theme"),
                ),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, help_text="AI-generated comprehensive summary")),
                ("ai_summary_pt", models.TextField(blank=True)),
                ("ai_insights", models.TextField(blank=True, help_text="AI-generated theological insights")),
                (
                    "ai_practical_application",
                    models.TextField(blank=True, help_text="AI-generated practical applications"),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                (
                    "source_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Topic keys that contributed to this theme",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "db_table": "theme",
                "ordering": ["-priority", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ThemeProgression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage_order", models.PositiveIntegerField(help_text="Order in the progression (1=earliest)")),
                (
                    "stage_name_en",
                    models.CharField(help_text="Name of this stage (e.g., 'Abrahamic Covenant')", max_length=200),
                ),
                ("stage_name_pt", models.CharField(blank=True, max_length=200)),
                ("description_en", models.TextField(help_text="How the theme is understood at this stage")),
                ("description_pt", models.TextField(blank=True)),
                (
                    "biblical_era",
                    models.CharField(
                        blank=True, help_text="Era (e.g., 'Patriarchal', 'Exodus', 'Monarchy')", max_length=100
                    ),
                ),
                ("primary_book", models.CharField(blank=True, help_text="Primary book for this stage", max_length=50)),
                ("key_reference", models.CharField(blank=True, help_text="Key verse for this stage", max_length=100)),
                (
                    "additional_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                (
                    "testament_focus",
                    models.CharField(
                        choices=[
                            ("old", "Old Testament"),
                            ("new", "New Testament"),
                            ("intertestamental", "Intertestamental"),
                        ],
                        default="old",
                        max_length=20,
                    ),
                ),
                (
                    "theological_development_en",
                    models.TextField(blank=True, help_text="What new understanding emerged at this stage"),
                ),
                ("theological_development_pt", models.TextField(blank=True)),
                (
                    "christological_connection_en",
                    models.TextField(blank=True, help_text="How this stage points to Christ"),
                ),
                ("christological_connection_pt", models.TextField(blank=True)),
                (
                    "is_fulfilled_in_christ",
                    models.BooleanField(default=False, help_text="Is this the stage where Christ fulfills the theme?"),
                ),
                ("eschatological_note", models.TextField(blank=True, help_text="Future/eschatological implications")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="progressions", to="themes.theme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme Progression",
                "verbose_name_plural": "Theme Progressions",
                "db_table": "theme_progression",
                "ordering": ["theme", "stage_order"],
                "unique_together": {("theme", "stage_order")},
            },
        ),
        migrations.CreateModel(
            name="ThemeCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_pt", models.CharField(blank=True, max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="themes.themecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme Category",
                "verbose_name_plural": "Theme Categories",
                "db_table": "theme_category",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.AddField(
            model_name="theme",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="themes",
                to="themes.themecategory",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="parent_theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent theme for hierarchy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_themes",
                to="themes.theme",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_doctrine",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary related doctrine",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="themes",
                to="theology.doctrine",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="theological_domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary theological domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="themes",
                to="theology.theologicaldomain",
            ),
        ),
        migrations.CreateModel(
            name="ThemeVerseLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relevance_score",
                    models.FloatField(default=1.0, help_text="How relevant is this theme to this verse (0-1)"),
                ),
                (
                    "is_primary_theme",
                    models.BooleanField(default=False, help_text="Is this the primary theme of the verse?"),
                ),
                ("context_note_en", models.TextField(blank=True, help_text="How the theme appears in this verse")),
                ("context_note_pt", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai", "AI Generated"),
                            ("manual", "Manual/Curated"),
                            ("imported", "Imported from Topic"),
                            ("cross_ref", "Cross-Reference Based"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(blank=True, help_text="AI analysis of how this theme appears in this verse"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progression_stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which progression stage does this verse belong to?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verse_links",
                        to="themes.themeprogression",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="verse_links", to="themes.theme"
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="theme_links_rich", to="bible.verse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme-Verse Link",
                "verbose_name_plural": "Theme-Verse Links",
                "db_table": "theme_verse_link",
                "indexes": [
                    models.Index(fields=["is_primary_theme"], name="theme_verse_is_prim_001d17_idx"),
                    models.Index(fields=["relevance_score"], name="theme_verse_relevan_b01a83_idx"),
                ],
                "unique_together": {("theme", "verse")},
            },
        ),
        migrations.CreateModel(
            name="ThemeRelatedTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("similar", "Similar/Related"),
                            ("contrasting", "Contrasting/Opposite"),
                            ("prerequisite", "Prerequisite For"),
                            ("develops_into", "Develops Into"),
                            ("fulfills", "Fulfills"),
                            ("aspect_of", "Aspect Of"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Explanation of the relationship")),
                (
                    "from_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="themes.theme",
                    ),
                ),
                (
                    "to_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "db_table": "theme_related_theme",
                "unique_together": {("from_theme", "to_theme", "relation_type")},
            },
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["status"], name="theme_status_bc8b95_idx"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["theological_domain"], name="theme_theolog_ff4a8d_idx"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["category"], name="theme_categor_b6ec8f_idx"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["label_normalized"], name="theme_label_n_3776b4_idx"),
        ),
    ]
