# Generated by Django 4.2.7 on 2025-12-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0021_crossref_and_topics_enriched"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "canonical_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier like 'PER:david', 'PLC:jerusalem'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("DEITY", "Deity"),
                            ("PLACE", "Place"),
                            ("ANGEL", "Angel"),
                            ("CONCEPT", "Concept"),
                            ("OBJECT", "Object"),
                            ("EVENT", "Event"),
                            ("LITERARY_WORK", "Literary Work"),
                            ("GROUP", "Group/Nation/Tribe"),
                            ("CREATURE", "Creature"),
                        ],
                        db_index=True,
                        help_text="Primary namespace (PERSON, PLACE, DEITY, etc.)",
                        max_length=20,
                    ),
                ),
                ("primary_name", models.CharField(help_text="Primary canonical name in English", max_length=200)),
                (
                    "primary_name_original",
                    models.CharField(
                        blank=True, help_text="Original language name (Hebrew/Greek/Aramaic)", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Brief description of the entity")),
                ("description_pt", models.TextField(blank=True, help_text="Description in Portuguese")),
                ("boost", models.FloatField(default=1.0, help_text="Search ranking boost (higher = more important)")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=50, help_text="Display priority (1-100, higher = more prominent)"
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list, help_text="Category tags for filtering")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("canonical", "Canonical"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, help_text="AI-generated comprehensive summary")),
                ("ai_summary_pt", models.TextField(blank=True, help_text="AI-generated summary in Portuguese")),
                (
                    "ai_theological_significance",
                    models.TextField(blank=True, help_text="AI analysis of theological importance"),
                ),
                (
                    "ai_historical_context",
                    models.TextField(blank=True, help_text="AI-generated historical/archaeological context"),
                ),
                ("etymology", models.TextField(blank=True, help_text="Name etymology and meaning")),
                ("hebrew_transliteration", models.CharField(blank=True, max_length=200)),
                ("greek_transliteration", models.CharField(blank=True, max_length=200)),
                (
                    "strongs_hebrew",
                    models.CharField(blank=True, help_text="Strong's Hebrew number if applicable", max_length=20),
                ),
                (
                    "strongs_greek",
                    models.CharField(blank=True, help_text="Strong's Greek number if applicable", max_length=20),
                ),
                (
                    "birth_year",
                    models.CharField(blank=True, help_text="Approximate birth year (e.g., '~1040 BC')", max_length=50),
                ),
                ("death_year", models.CharField(blank=True, help_text="Approximate death year", max_length=50)),
                (
                    "active_period",
                    models.CharField(
                        blank=True, help_text="Period of primary activity (e.g., '1010-970 BC')", max_length=100
                    ),
                ),
                (
                    "biblical_era",
                    models.CharField(
                        blank=True, help_text="Biblical era (e.g., 'United Monarchy', 'Exile')", max_length=100
                    ),
                ),
                ("study_value", models.PositiveIntegerField(default=50, help_text="Value for Bible study (1-100)")),
                (
                    "difficulty_level",
                    models.PositiveIntegerField(default=50, help_text="Complexity level (1-100, 100=most complex)"),
                ),
                (
                    "verse_count",
                    models.PositiveIntegerField(default=0, help_text="Number of verses mentioning this entity"),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                (
                    "is_type_of_christ",
                    models.BooleanField(default=False, help_text="Is this entity a type/shadow of Christ?"),
                ),
                ("typology_explanation", models.TextField(blank=True, help_text="How this entity prefigures Christ")),
                ("wikidata_id", models.CharField(blank=True, max_length=20)),
                ("wikipedia_url", models.URLField(blank=True)),
                ("easton_bible_dict_url", models.URLField(blank=True)),
                ("hitchcock_url", models.URLField(blank=True)),
                (
                    "source_topics",
                    models.JSONField(
                        blank=True, default=list, help_text="Original topic keys that referenced this entity"
                    ),
                ),
                ("source_gazetteer", models.CharField(blank=True, help_text="Source gazetteer file", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canonical Entity",
                "verbose_name_plural": "Canonical Entities",
                "db_table": "canonical_entity",
                "ordering": ["-priority", "primary_name"],
            },
        ),
        migrations.CreateModel(
            name="EntityCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("name_pt", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="entities.entitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Category",
                "verbose_name_plural": "Entity Categories",
                "db_table": "entity_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EntityRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("shepherd", "Shepherd"),
                            ("farmer", "Farmer"),
                            ("fisherman", "Fisherman"),
                            ("carpenter", "Carpenter"),
                            ("tentmaker", "Tentmaker"),
                            ("soldier", "Soldier"),
                            ("warrior", "Warrior"),
                            ("king", "King"),
                            ("queen", "Queen"),
                            ("prince", "Prince"),
                            ("princess", "Princess"),
                            ("priest", "Priest"),
                            ("high_priest", "High Priest"),
                            ("levite", "Levite"),
                            ("prophet", "Prophet"),
                            ("prophetess", "Prophetess"),
                            ("judge", "Judge"),
                            ("apostle", "Apostle"),
                            ("disciple", "Disciple"),
                            ("teacher", "Teacher/Rabbi"),
                            ("scribe", "Scribe"),
                            ("pharisee", "Pharisee"),
                            ("sadducee", "Sadducee"),
                            ("elder", "Elder"),
                            ("deacon", "Deacon"),
                            ("evangelist", "Evangelist"),
                            ("servant", "Servant"),
                            ("slave", "Slave"),
                            ("wife", "Wife"),
                            ("husband", "Husband"),
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("child", "Child"),
                            ("widow", "Widow"),
                            ("patriarch", "Patriarch"),
                            ("matriarch", "Matriarch"),
                            ("ancestor", "Ancestor of Messiah"),
                            ("musician", "Musician"),
                            ("psalmist", "Psalmist"),
                            ("cupbearer", "Cupbearer"),
                            ("governor", "Governor"),
                            ("tax_collector", "Tax Collector"),
                            ("physician", "Physician"),
                            ("sorcerer", "Sorcerer/Magician"),
                            ("pre_existent", "Pre-existent (Logos)"),
                            ("creator", "Creator"),
                            ("incarnate", "Incarnate/Human"),
                            ("messiah", "Messiah/Christ"),
                            ("lamb", "Sacrificial Lamb"),
                            ("risen", "Risen Lord"),
                            ("ascended", "Ascended King"),
                            ("intercessor", "Intercessor"),
                            ("judge_divine", "Divine Judge"),
                            ("returning", "Returning King"),
                            ("messenger", "Messenger"),
                            ("guardian", "Guardian"),
                            ("warrior_angel", "Warrior Angel"),
                            ("seraph", "Seraph"),
                            ("cherub", "Cherub"),
                            ("archangel", "Archangel"),
                            ("capital", "Capital City"),
                            ("temple_site", "Temple Site"),
                            ("battlefield", "Battlefield"),
                            ("refuge", "City of Refuge"),
                            ("sanctuary", "Sanctuary"),
                            ("wilderness", "Wilderness"),
                            ("promised_land", "Promised Land"),
                            ("exile", "Place of Exile"),
                            ("other", "Other"),
                        ],
                        help_text="Type of role (king, prophet, shepherd, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "role_label",
                    models.CharField(help_text="Human-readable label (e.g., 'King of Israel')", max_length=200),
                ),
                ("role_label_pt", models.CharField(blank=True, help_text="Label in Portuguese", max_length=200)),
                (
                    "period_start",
                    models.CharField(blank=True, help_text="Approximate start (e.g., '~1010 BC')", max_length=100),
                ),
                ("period_end", models.CharField(blank=True, help_text="Approximate end", max_length=100)),
                (
                    "period_label",
                    models.CharField(
                        blank=True, help_text="Human-readable period (e.g., 'Reign of David')", max_length=200
                    ),
                ),
                (
                    "period_label_pt",
                    models.CharField(blank=True, help_text="Period label in Portuguese", max_length=200),
                ),
                (
                    "start_reference",
                    models.CharField(
                        blank=True, help_text="First verse reference for this role (e.g., '2 Sam 5:3')", max_length=50
                    ),
                ),
                (
                    "end_reference",
                    models.CharField(blank=True, help_text="Last verse reference for this role", max_length=50),
                ),
                (
                    "narrative_order",
                    models.PositiveIntegerField(default=0, help_text="Order in the biblical narrative (0=earliest)"),
                ),
                ("description", models.TextField(blank=True, help_text="Description of this role")),
                ("description_pt", models.TextField(blank=True, help_text="Description in Portuguese")),
                (
                    "theological_significance",
                    models.TextField(blank=True, help_text="Why this role is theologically important"),
                ),
                (
                    "is_typological",
                    models.BooleanField(default=False, help_text="Does this role prefigure Christ or NT concept?"),
                ),
                ("typology_explanation", models.TextField(blank=True, help_text="How this role prefigures Christ")),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_insights", models.TextField(blank=True, help_text="AI-generated insights about this role")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="entities.canonicalentity"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Role",
                "verbose_name_plural": "Entity Roles",
                "db_table": "entity_role",
                "ordering": ["entity", "narrative_order"],
            },
        ),
        migrations.CreateModel(
            name="EntityVerseLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicitly Named"),
                            ("implicit", "Implicitly Referenced"),
                            ("title", "By Title Only"),
                            ("pronoun", "Pronoun Reference"),
                            ("typological", "Typological Reference"),
                        ],
                        default="explicit",
                        max_length=20,
                    ),
                ),
                ("context_note", models.TextField(blank=True, help_text="How is the entity mentioned in this verse?")),
                ("context_note_pt", models.TextField(blank=True)),
                (
                    "relevance",
                    models.FloatField(default=1.0, help_text="How central is this entity to the verse (0-1)"),
                ),
                (
                    "is_primary_subject",
                    models.BooleanField(default=False, help_text="Is this entity the primary subject of the verse?"),
                ),
                (
                    "ai_analysis",
                    models.TextField(blank=True, help_text="AI analysis of the entity in this verse context"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verse_links",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which role the entity had in this verse",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verse_links",
                        to="entities.entityrole",
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entity_links", to="bible.verse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity-Verse Link",
                "verbose_name_plural": "Entity-Verse Links",
                "db_table": "entity_verse_link",
            },
        ),
        migrations.CreateModel(
            name="EntityTimeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birth", "Birth"),
                            ("death", "Death"),
                            ("calling", "Divine Calling"),
                            ("conversion", "Conversion"),
                            ("anointing", "Anointing"),
                            ("marriage", "Marriage"),
                            ("coronation", "Coronation"),
                            ("exile", "Exile"),
                            ("return", "Return"),
                            ("miracle", "Miracle"),
                            ("prophecy", "Prophecy Given/Received"),
                            ("battle", "Battle"),
                            ("treaty", "Treaty/Covenant"),
                            ("sin", "Sin/Failure"),
                            ("repentance", "Repentance"),
                            ("blessing", "Blessing Received"),
                            ("judgment", "Judgment"),
                            ("founding", "Founding (place)"),
                            ("destruction", "Destruction (place)"),
                            ("rebuilding", "Rebuilding (place)"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(help_text="Event title (e.g., 'David anointed by Samuel')", max_length=200)),
                ("title_pt", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True)),
                (
                    "date_approximate",
                    models.CharField(blank=True, help_text="Approximate date (e.g., '~1000 BC')", max_length=100),
                ),
                ("year_start", models.IntegerField(blank=True, help_text="Start year (negative for BC)", null=True)),
                ("year_end", models.IntegerField(blank=True, help_text="End year if event spans time", null=True)),
                (
                    "primary_reference",
                    models.CharField(blank=True, help_text="Primary verse reference", max_length=100),
                ),
                (
                    "additional_references",
                    models.JSONField(blank=True, default=list, help_text="Additional verse references"),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, help_text="Location name (if entity not available)", max_length=200),
                ),
                (
                    "chronological_order",
                    models.PositiveIntegerField(default=0, help_text="Order in timeline (0=earliest)"),
                ),
                ("theological_significance", models.TextField(blank=True)),
                ("is_turning_point", models.BooleanField(default=False, help_text="Is this a major turning point?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where this event occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_at_location",
                        to="entities.canonicalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Timeline Event",
                "verbose_name_plural": "Entity Timeline Events",
                "db_table": "entity_timeline",
                "ordering": ["entity", "chronological_order"],
            },
        ),
        migrations.CreateModel(
            name="EntityRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parent_of", "Parent of"),
                            ("child_of", "Child of"),
                            ("sibling", "Sibling"),
                            ("spouse_of", "Spouse of"),
                            ("ancestor_of", "Ancestor of"),
                            ("descendant_of", "Descendant of"),
                            ("king_of", "King of"),
                            ("subject_of", "Subject of"),
                            ("servant_of", "Servant of"),
                            ("master_of", "Master of"),
                            ("leader_of", "Leader of"),
                            ("member_of", "Member of"),
                            ("disciple_of", "Disciple of"),
                            ("teacher_of", "Teacher of"),
                            ("successor_of", "Successor of"),
                            ("predecessor_of", "Predecessor of"),
                            ("anointed_by", "Anointed by"),
                            ("enemy_of", "Enemy of"),
                            ("ally_of", "Ally of"),
                            ("betrayed_by", "Betrayed by"),
                            ("killed_by", "Killed by"),
                            ("persecutor_of", "Persecutor of"),
                            ("born_in", "Born in"),
                            ("died_in", "Died in"),
                            ("lived_in", "Lived in"),
                            ("traveled_to", "Traveled to"),
                            ("exiled_to", "Exiled to"),
                            ("conquered", "Conquered"),
                            ("founded", "Founded"),
                            ("built", "Built"),
                            ("type_of", "Type/Shadow of"),
                            ("antitype_of", "Antitype/Fulfillment of"),
                            ("foreshadows", "Foreshadows"),
                            ("fulfills", "Fulfills"),
                            ("parallels", "Parallels"),
                            ("contrasts", "Contrasts with"),
                            ("associated_with", "Associated with"),
                            ("part_of", "Part of"),
                            ("contemporary_of", "Contemporary of"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of this relationship")),
                ("description_pt", models.TextField(blank=True)),
                ("period_start", models.CharField(blank=True, max_length=100)),
                ("period_end", models.CharField(blank=True, max_length=100)),
                ("primary_reference", models.CharField(blank=True, max_length=100)),
                ("additional_references", models.JSONField(blank=True, default=list)),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("certain", "Certain"),
                            ("probable", "Probable"),
                            ("possible", "Possible"),
                            ("debated", "Debated"),
                        ],
                        default="certain",
                        max_length=20,
                    ),
                ),
                ("is_typological", models.BooleanField(default=False, help_text="Is this a typological relationship?")),
                ("theological_note", models.TextField(blank=True)),
                (
                    "source_topic",
                    models.CharField(
                        blank=True, help_text="Original topic where relationship was found", max_length=100
                    ),
                ),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_analysis", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="entities.canonicalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Relationship",
                "verbose_name_plural": "Entity Relationships",
                "db_table": "entity_relationship",
            },
        ),
        migrations.CreateModel(
            name="EntityCategoryLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relevance", models.FloatField(default=1.0, help_text="How relevant is this category (0-1)")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="entities.entitycategory",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="entities.canonicalentity",
                    ),
                ),
            ],
            options={
                "db_table": "entity_category_link",
            },
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "language_code",
                    models.CharField(blank=True, help_text="ISO language code (en, pt, he, el, etc.)", max_length=10),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Is this the primary name in this language?"),
                ),
                ("is_transliteration", models.BooleanField(default=False, help_text="Is this a transliteration?")),
                (
                    "usage_note",
                    models.CharField(blank=True, help_text="Context where this name is used", max_length=200),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Language of this alias",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bible.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Alias",
                "verbose_name_plural": "Entity Aliases",
                "db_table": "entity_alias",
            },
        ),
        migrations.AddIndex(
            model_name="canonicalentity",
            index=models.Index(fields=["namespace", "status"], name="canonical_e_namespa_e7c501_idx"),
        ),
        migrations.AddIndex(
            model_name="canonicalentity",
            index=models.Index(fields=["boost"], name="canonical_e_boost_4c28fa_idx"),
        ),
        migrations.AddIndex(
            model_name="canonicalentity",
            index=models.Index(fields=["is_type_of_christ"], name="canonical_e_is_type_0269f0_idx"),
        ),
        migrations.AddIndex(
            model_name="entityverselink",
            index=models.Index(fields=["mention_type"], name="entity_vers_mention_444ba4_idx"),
        ),
        migrations.AddIndex(
            model_name="entityverselink",
            index=models.Index(fields=["is_primary_subject"], name="entity_vers_is_prim_e437d1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entityverselink",
            unique_together={("entity", "verse")},
        ),
        migrations.AddIndex(
            model_name="entityrole",
            index=models.Index(fields=["role_type"], name="entity_role_role_ty_1b9f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="entityrole",
            index=models.Index(fields=["entity", "narrative_order"], name="entity_role_entity__ce6066_idx"),
        ),
        migrations.AddIndex(
            model_name="entityrelationship",
            index=models.Index(fields=["relationship_type"], name="entity_rela_relatio_7b59c0_idx"),
        ),
        migrations.AddIndex(
            model_name="entityrelationship",
            index=models.Index(fields=["source", "target"], name="entity_rela_source__94e32f_idx"),
        ),
        migrations.AddIndex(
            model_name="entityrelationship",
            index=models.Index(fields=["is_typological"], name="entity_rela_is_typo_83a088_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="entitycategorylink",
            unique_together={("entity", "category")},
        ),
        migrations.AddIndex(
            model_name="entityalias",
            index=models.Index(fields=["name"], name="entity_alia_name_f4e347_idx"),
        ),
        migrations.AddIndex(
            model_name="entityalias",
            index=models.Index(fields=["language_code"], name="entity_alia_languag_74ed28_idx"),
        ),
    ]
