# Generated by Django 4.2.7 on 2026-03-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0002_entity_person_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canonicalentity",
            name="namespace",
            field=models.CharField(
                choices=[
                    ("PERSON", "Person"),
                    ("DEITY", "Deity"),
                    ("PLACE", "Place"),
                    ("ANGEL", "Angel"),
                    ("CONCEPT", "Concept"),
                    ("OBJECT", "Object"),
                    ("EVENT", "Event"),
                    ("LITERARY_WORK", "Literary Work"),
                    ("GROUP", "Group/Nation/Tribe"),
                    ("CREATURE", "Creature"),
                    ("PLANT", "Plant"),
                    ("RITUAL", "Ritual/Ceremony"),
                    ("LITERARY_FORM", "Literary Form"),
                ],
                db_index=True,
                help_text="Primary namespace (PERSON, PLACE, DEITY, etc.)",
                max_length=20,
            ),
        ),
    ]
