# Generated by Django 4.2.7 on 2026-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0003_add_plant_ritual_literary_form_namespaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityverselink",
            name="match_words",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Words in the verse text that reference this entity (for inline highlighting)",
            ),
        ),
    ]
