# Generated by Django 4.2.7 on 2025-12-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("themes", "0001_themes_enriched"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bible", "0022_initial_models"),
        ("theology", "0001_theology_domain"),
        ("entities", "0001_entities_and_symbols"),
        ("symbols", "0001_entities_and_symbols"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Full canonical name (e.g., 'Augustine of Hippo')", max_length=200),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="Common short name or title (e.g., 'Augustine')", max_length=100
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(
                        blank=True, help_text="Latin name if applicable (e.g., 'Aurelius Augustinus')", max_length=200
                    ),
                ),
                ("hebrew_name", models.CharField(blank=True, help_text="Hebrew name if applicable", max_length=200)),
                ("greek_name", models.CharField(blank=True, help_text="Greek name if applicable", max_length=200)),
                (
                    "also_known_as",
                    models.JSONField(blank=True, default=list, help_text="Alternative names and titles as JSON array"),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("biblical", "Biblical Author"),
                            ("apostolic", "Apostolic Father"),
                            ("church_father", "Church Father"),
                            ("desert_father", "Desert Father"),
                            ("medieval", "Medieval Theologian"),
                            ("scholastic", "Scholastic"),
                            ("reformation", "Reformation Era"),
                            ("puritan", "Puritan"),
                            ("modern", "Modern Commentator"),
                            ("contemporary", "Contemporary Scholar"),
                            ("legendary", "Traditional/Legendary"),
                        ],
                        help_text="Primary category of author",
                        max_length=30,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        help_text="More specific categorization (e.g., 'Cappadocian Father')",
                        max_length=100,
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(blank=True, help_text="Approximate birth year (negative for BC)", null=True),
                ),
                (
                    "death_year",
                    models.IntegerField(
                        blank=True, help_text="Approximate death year (use 'AD' format, e.g., 430 for AD430)", null=True
                    ),
                ),
                (
                    "century",
                    models.CharField(
                        blank=True, help_text="Primary century (e.g., '4th century', '1st century BC')", max_length=50
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, help_text="Historical period description (e.g., 'AD397', 'AD430')", max_length=100
                    ),
                ),
                (
                    "era",
                    models.CharField(
                        blank=True, help_text="Broader era (e.g., 'Patristic Era', 'Reformation')", max_length=100
                    ),
                ),
                ("birthplace", models.CharField(blank=True, help_text="City/region of birth", max_length=200)),
                (
                    "primary_location",
                    models.CharField(blank=True, help_text="Where they primarily worked/taught", max_length=200),
                ),
                (
                    "cultural_context",
                    models.TextField(blank=True, help_text="Cultural and political context of their work"),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, help_text="Modern nationality equivalent or ancient region", max_length=100
                    ),
                ),
                (
                    "tradition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("eastern", "Eastern"),
                            ("western", "Western/Latin"),
                            ("oriental", "Oriental Orthodox"),
                            ("catholic", "Roman Catholic"),
                            ("orthodox", "Eastern Orthodox"),
                            ("reformed", "Reformed/Calvinist"),
                            ("lutheran", "Lutheran"),
                            ("anglican", "Anglican"),
                            ("baptist", "Baptist"),
                            ("methodist", "Methodist"),
                            ("pentecostal", "Pentecostal"),
                            ("evangelical", "Evangelical"),
                            ("other", "Other"),
                        ],
                        help_text="Theological/ecclesiastical tradition",
                        max_length=100,
                    ),
                ),
                (
                    "theological_school",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("antiochene", "Antiochene School"),
                            ("alexandrian", "Alexandrian School"),
                            ("cappadocian", "Cappadocian"),
                            ("scholastic", "Scholastic"),
                            ("reformed", "Reformed Orthodox"),
                            ("dispensational", "Dispensationalist"),
                            ("covenant", "Covenant Theology"),
                            ("historical_critical", "Historical-Critical"),
                            ("narrative", "Narrative Theology"),
                            ("other", "Other"),
                        ],
                        help_text="Theological school or approach",
                        max_length=200,
                    ),
                ),
                (
                    "ecclesiastical_rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pope", "Pope"),
                            ("patriarch", "Patriarch"),
                            ("archbishop", "Archbishop"),
                            ("bishop", "Bishop"),
                            ("presbyter", "Presbyter/Priest"),
                            ("deacon", "Deacon"),
                            ("monk", "Monk"),
                            ("abbot", "Abbot"),
                            ("professor", "Professor"),
                            ("pastor", "Pastor"),
                            ("layperson", "Layperson"),
                        ],
                        help_text="Church office or position",
                        max_length=100,
                    ),
                ),
                (
                    "feast_day",
                    models.CharField(
                        blank=True, help_text="Liturgical feast day if saint (e.g., 'August 28')", max_length=50
                    ),
                ),
                (
                    "is_saint",
                    models.BooleanField(default=False, help_text="Whether recognized as saint in any tradition"),
                ),
                (
                    "is_doctor_of_church",
                    models.BooleanField(default=False, help_text="Whether recognized as Doctor of the Church"),
                ),
                (
                    "biblical_role",
                    models.CharField(
                        blank=True,
                        help_text="Role in biblical narrative (prophet, apostle, king, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "biblical_period",
                    models.CharField(
                        blank=True, help_text="Biblical historical period (United Kingdom, Exile, etc.)", max_length=100
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(blank=True, default=list, help_text="Areas of expertise as JSON array"),
                ),
                (
                    "major_works",
                    models.JSONField(blank=True, default=list, help_text="List of major works as JSON array"),
                ),
                (
                    "primary_hermeneutic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("literal", "Literal/Grammatical-Historical"),
                            ("allegorical", "Allegorical"),
                            ("typological", "Typological"),
                            ("moral", "Moral/Tropological"),
                            ("anagogical", "Anagogical/Eschatological"),
                            ("fourfold", "Fourfold Sense (Quadriga)"),
                            ("christological", "Christocentric"),
                            ("redemptive_historical", "Redemptive-Historical"),
                            ("canonical", "Canonical"),
                            ("narrative", "Narrative"),
                            ("socio_rhetorical", "Socio-Rhetorical"),
                            ("mixed", "Mixed/Multiple"),
                        ],
                        help_text="Primary interpretive approach",
                        max_length=50,
                    ),
                ),
                ("hermeneutical_notes", models.TextField(blank=True, help_text="Notes on interpretive methodology")),
                ("modern_significance", models.TextField(blank=True, help_text="Why this author matters today")),
                ("scholarly_consensus", models.TextField(blank=True, help_text="Current academic view of their work")),
                (
                    "controversies",
                    models.TextField(blank=True, help_text="Theological controversies associated with this author"),
                ),
                ("biography_summary", models.TextField(blank=True, help_text="Concise biographical summary")),
                ("biography_pt", models.TextField(blank=True, help_text="Biographical summary in Portuguese")),
                ("theological_contributions", models.TextField(blank=True, help_text="Key theological contributions")),
                ("historical_impact", models.TextField(blank=True, help_text="Impact on church history")),
                ("famous_quotes", models.JSONField(blank=True, default=list, help_text="Notable quotes as JSON array")),
                (
                    "reliability_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent - Well documented"),
                            ("good", "Good - Generally reliable"),
                            ("fair", "Fair - Some uncertainty"),
                            ("poor", "Poor - Limited information"),
                            ("legendary", "Legendary - Mostly traditional"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("portrait_image", models.URLField(blank=True, help_text="URL to author's portrait/icon")),
                (
                    "portrait_description",
                    models.CharField(blank=True, help_text="Alt text for portrait", max_length=300),
                ),
                (
                    "portrait_source",
                    models.CharField(blank=True, help_text="Source/attribution for image", max_length=200),
                ),
                (
                    "portrait_license",
                    models.CharField(blank=True, help_text="Image license (CC, Public Domain, etc)", max_length=100),
                ),
                (
                    "episcopal_appointment",
                    models.IntegerField(blank=True, help_text="Year of episcopal appointment", null=True),
                ),
                (
                    "presbyterial_appointment",
                    models.IntegerField(blank=True, help_text="Year of presbyterial appointment", null=True),
                ),
                ("papal_election", models.IntegerField(blank=True, help_text="Year of papal election", null=True)),
                (
                    "historical_sources",
                    models.JSONField(
                        blank=True, default=list, help_text="Historical sources and editions as JSON array"
                    ),
                ),
                ("wikipedia_url", models.URLField(blank=True)),
                ("ccel_url", models.URLField(blank=True, help_text="Christian Classics Ethereal Library URL")),
                ("newadvent_url", models.URLField(blank=True, help_text="New Advent Catholic Encyclopedia URL")),
                (
                    "external_links",
                    models.JSONField(blank=True, default=list, help_text="Additional reference links as JSON array"),
                ),
                ("bibliography", models.TextField(blank=True, help_text="Key academic sources")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biblical_books_authored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Books traditionally attributed to this author",
                        related_name="traditional_authors",
                        to="bible.canonicalbook",
                    ),
                ),
                ("contemporary_with", models.ManyToManyField(blank=True, to="commentaries.author")),
                (
                    "influenced_by",
                    models.ManyToManyField(blank=True, related_name="influenced", to="commentaries.author"),
                ),
                (
                    "primary_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentary_authors",
                        to="bible.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "commentaries_author",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommentaryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField()),
                (
                    "original_reference",
                    models.CharField(
                        blank=True, help_text="Original reference format from source (e.g., 'JN 1:1')", max_length=100
                    ),
                ),
                ("title", models.CharField(blank=True, help_text="Entry title if available", max_length=300)),
                ("body_text", models.TextField(help_text="Plain text content of commentary")),
                ("body_html", models.TextField(blank=True, default="", help_text="HTML formatted content")),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beautifulsoup", "BeautifulSoup scraping"),
                            ("firecrawl", "Firecrawl extraction"),
                            ("api", "API import"),
                            ("manual", "Manual entry"),
                            ("ocr", "OCR from scanned text"),
                        ],
                        help_text="How this content was extracted",
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField(blank=True, help_text="URL where this commentary was found")),
                ("full_content_url", models.URLField(blank=True, help_text="URL to full content if truncated")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("full", "Full content"),
                            ("excerpt", "Excerpt only"),
                            ("summary", "Summary"),
                            ("reference", "Reference/Cross-reference"),
                        ],
                        default="full",
                        help_text="Type of content captured",
                        max_length=20,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=True, help_text="Whether this entry is complete (vs. excerpt/summary)"),
                ),
                (
                    "original_language",
                    models.CharField(
                        blank=True,
                        help_text="Original language of text (e.g., 'Latin', 'Greek', 'English')",
                        max_length=20,
                    ),
                ),
                ("word_count", models.IntegerField(blank=True, help_text="Approximate word count", null=True)),
                (
                    "reading_time",
                    models.CharField(
                        blank=True, help_text="Estimated reading time (e.g., '< 1 min', '5 mins')", max_length=20
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(blank=True, help_text="Data quality/accuracy score (0.0-1.0)", null=True),
                ),
                (
                    "commentary_number",
                    models.CharField(
                        blank=True, help_text="Position in source (e.g., '1/12' for first of 12)", max_length=20
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order for display when multiple entries exist"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific author (for multi-author sources)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentary_entries",
                        to="commentaries.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentary_entries",
                        to="bible.canonicalbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary Entry",
                "verbose_name_plural": "Commentary Entries",
                "db_table": "commentaries_entry",
                "ordering": ["source", "book__canonical_order", "chapter", "verse_start", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="CommentaryTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(help_text="Translated content")),
                ("content_html", models.TextField(blank=True, help_text="Translated content with HTML formatting")),
                ("title", models.CharField(blank=True, help_text="Translated title if available", max_length=300)),
                (
                    "translation_method",
                    models.CharField(
                        choices=[
                            ("ai_gpt4", "GPT-4"),
                            ("ai_gpt4o", "GPT-4o"),
                            ("ai_gpt4o_mini", "GPT-4o-mini"),
                            ("ai_claude", "Claude"),
                            ("ai_gemini", "Gemini"),
                            ("human", "Human translator"),
                            ("existing", "Pre-existing translation"),
                        ],
                        default="ai_gpt4o_mini",
                        help_text="How this translation was created",
                        max_length=50,
                    ),
                ),
                (
                    "translation_model",
                    models.CharField(blank=True, help_text="Specific model used (e.g., 'gpt-4o-mini')", max_length=100),
                ),
                (
                    "translated_at",
                    models.DateTimeField(blank=True, help_text="When translation was performed", null=True),
                ),
                (
                    "translator_notes",
                    models.TextField(blank=True, help_text="Notes about translation choices or difficulties"),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, help_text="Whether translation has been human-reviewed"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, help_text="Quality assessment (0.0-1.0)", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="commentaries.commentaryentry",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentary_translations",
                        to="bible.language",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary Translation",
                "verbose_name_plural": "Commentary Translations",
                "db_table": "commentaries_translation",
                "ordering": ["entry", "language"],
            },
        ),
        migrations.CreateModel(
            name="CommentarySource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (e.g., 'Matthew Henry Complete Commentary')", max_length=200, unique=True
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'MHCC', 'TSK', 'CATENA')", max_length=40, unique=True
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(blank=True, help_text="Subtitle or additional description", max_length=300),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("patristic", "Patristic Commentary"),
                            ("medieval", "Medieval Commentary"),
                            ("reformation", "Reformation Commentary"),
                            ("puritan", "Puritan Commentary"),
                            ("modern_devotional", "Modern Devotional"),
                            ("modern_academic", "Modern Academic"),
                            ("cross_reference", "Cross-Reference System"),
                            ("study_bible", "Study Bible Notes"),
                            ("catena", "Catena (Chain) Commentary"),
                            ("homily", "Homiletical Collection"),
                        ],
                        default="modern_devotional",
                        help_text="Type of commentary source",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", help_text="Primary URL for this source")),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True, help_text="Description in Portuguese")),
                (
                    "publication_year",
                    models.IntegerField(blank=True, help_text="Year of publication or primary edition", null=True),
                ),
                (
                    "original_publication_year",
                    models.IntegerField(blank=True, help_text="Year of original publication (if different)", null=True),
                ),
                ("publisher", models.CharField(blank=True, help_text="Publisher name", max_length=200)),
                ("editor", models.CharField(blank=True, help_text="Editor(s) name", max_length=200)),
                (
                    "coverage",
                    models.CharField(
                        choices=[
                            ("whole_bible", "Whole Bible"),
                            ("old_testament", "Old Testament Only"),
                            ("new_testament", "New Testament Only"),
                            ("pentateuch", "Pentateuch"),
                            ("gospels", "Gospels"),
                            ("pauline", "Pauline Epistles"),
                            ("specific_books", "Specific Books"),
                        ],
                        default="whole_bible",
                        help_text="Biblical coverage of this source",
                        max_length=50,
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        blank=True, help_text="Type of authors (e.g., 'Church Fathers', 'Reformation')", max_length=50
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True, help_text="URL to cover image/icon for UI display")),
                (
                    "icon_class",
                    models.CharField(blank=True, help_text="CSS icon class for UI (e.g., 'fa-book')", max_length=100),
                ),
                (
                    "theme_color",
                    models.CharField(blank=True, help_text="Hex color for UI theming (e.g., '#8B4513')", max_length=7),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether available for use")),
                ("is_featured", models.BooleanField(default=False, help_text="Whether to feature prominently in UI")),
                ("is_free", models.BooleanField(default=True, help_text="Whether freely available")),
                (
                    "requires_attribution",
                    models.BooleanField(default=True, help_text="Whether attribution is required"),
                ),
                ("entry_count", models.IntegerField(default=0, help_text="Number of commentary entries")),
                (
                    "verse_coverage_percent",
                    models.FloatField(blank=True, help_text="Percentage of Bible verses covered (0-100)", null=True),
                ),
                (
                    "average_entry_length",
                    models.IntegerField(blank=True, help_text="Average word count per entry", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="All authors (for multi-author works like Catena)",
                        related_name="contributed_sources",
                        to="commentaries.author",
                    ),
                ),
                (
                    "covered_books",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific books covered (if not whole Bible)",
                        related_name="commentary_source_coverage",
                        to="bible.canonicalbook",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentary_sources",
                        to="bible.language",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentary_sources",
                        to="bible.license",
                    ),
                ),
                (
                    "primary_author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary author (for single-author works)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_sources",
                        to="commentaries.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary Source",
                "verbose_name_plural": "Commentary Sources",
                "db_table": "commentaries_source",
                "ordering": ["short_code"],
            },
        ),
        migrations.CreateModel(
            name="CommentaryReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("quotes", "Quotes directly"),
                            ("paraphrases", "Paraphrases"),
                            ("responds_to", "Responds to"),
                            ("agrees_with", "Agrees with"),
                            ("disagrees_with", "Disagrees with"),
                            ("builds_upon", "Builds upon"),
                            ("parallel", "Parallel interpretation"),
                            ("contrasts", "Contrasting interpretation"),
                        ],
                        help_text="Nature of the reference",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of how entries are related")),
                ("confidence", models.FloatField(default=1.0, help_text="Confidence in this reference (0.0-1.0)")),
                (
                    "is_explicit",
                    models.BooleanField(default=True, help_text="Whether reference is explicit vs. inferred"),
                ),
                (
                    "detected_by",
                    models.CharField(
                        blank=True, help_text="How reference was detected (manual, AI, etc.)", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_references",
                        to="commentaries.commentaryentry",
                    ),
                ),
                (
                    "target_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_references",
                        to="commentaries.commentaryentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary Reference",
                "verbose_name_plural": "Commentary References",
                "db_table": "commentaries_reference",
            },
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="commentaries.commentarysource"
            ),
        ),
        migrations.CreateModel(
            name="CommentaryEnrichment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "summary_one_sentence",
                    models.TextField(blank=True, help_text="One-sentence summary of the commentary"),
                ),
                ("summary_abstract", models.TextField(blank=True, help_text="Extended abstract/summary")),
                (
                    "summary_key_points",
                    models.JSONField(blank=True, default=list, help_text="Key points as JSON array"),
                ),
                ("summary_one_sentence_pt", models.TextField(blank=True)),
                ("summary_abstract_pt", models.TextField(blank=True)),
                ("summary_key_points_pt", models.JSONField(blank=True, default=list)),
                ("thesis", models.TextField(blank=True, help_text="Main thesis/argument of the commentary")),
                (
                    "arguments",
                    models.JSONField(blank=True, default=list, help_text="Supporting arguments as JSON array"),
                ),
                (
                    "objections",
                    models.JSONField(blank=True, default=list, help_text="Objections addressed as JSON array"),
                ),
                ("conclusion", models.TextField(blank=True, help_text="Conclusion of the argument")),
                ("thesis_pt", models.TextField(blank=True)),
                ("arguments_pt", models.JSONField(blank=True, default=list)),
                ("conclusion_pt", models.TextField(blank=True)),
                (
                    "doctrines",
                    models.JSONField(
                        blank=True, default=list, help_text="Doctrines discussed (e.g., ['Trinity', 'Christology'])"
                    ),
                ),
                (
                    "traditions",
                    models.JSONField(
                        blank=True, default=list, help_text="Theological traditions (e.g., ['Latin', 'Eastern'])"
                    ),
                ),
                (
                    "church_fathers_referenced",
                    models.JSONField(blank=True, default=list, help_text="Church Fathers referenced in commentary"),
                ),
                (
                    "scripture_references",
                    models.JSONField(blank=True, default=list, help_text="Scripture passages referenced"),
                ),
                (
                    "theological_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("literal", "Literal/Historical"),
                            ("allegorical", "Allegorical"),
                            ("typological", "Typological"),
                            ("moral", "Moral/Tropological"),
                            ("anagogical", "Anagogical"),
                            ("fourfold", "Fourfold Sense"),
                            ("mixed", "Mixed Methods"),
                        ],
                        help_text="Primary interpretive method used",
                        max_length=50,
                    ),
                ),
                (
                    "controversies",
                    models.JSONField(blank=True, default=list, help_text="Theological controversies addressed"),
                ),
                ("spiritual_theme", models.CharField(blank=True, help_text="Central spiritual theme", max_length=200)),
                ("spiritual_theme_pt", models.CharField(blank=True, max_length=200)),
                ("practical_reflection", models.TextField(blank=True, help_text="Practical application for readers")),
                ("practical_reflection_pt", models.TextField(blank=True)),
                ("devotional_value", models.TextField(blank=True, help_text="Devotional/prayer implications")),
                (
                    "enrichment_model",
                    models.CharField(blank=True, help_text="AI model used (e.g., 'gpt-4o-mini')", max_length=100),
                ),
                (
                    "enrichment_timestamp",
                    models.DateTimeField(blank=True, help_text="When enrichment was generated", null=True),
                ),
                (
                    "enrichment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("partial", "Partial (some fields failed)"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrichment_error", models.TextField(blank=True, help_text="Error message if enrichment failed")),
                (
                    "enrichment_version",
                    models.CharField(default="1.0", help_text="Version of enrichment pipeline used", max_length=20),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Whether enrichment has been human-verified"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment",
                        to="commentaries.commentaryentry",
                    ),
                ),
                (
                    "related_doctrines",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Doctrines discussed in commentary",
                        related_name="commentary_enrichments",
                        to="theology.doctrine",
                    ),
                ),
                (
                    "related_entities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Biblical entities discussed in commentary",
                        related_name="commentary_enrichments",
                        to="entities.canonicalentity",
                    ),
                ),
                (
                    "related_symbols",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Symbols interpreted in commentary",
                        related_name="commentary_enrichments",
                        to="symbols.biblicalsymbol",
                    ),
                ),
                (
                    "related_themes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Themes addressed in commentary",
                        related_name="commentary_enrichments",
                        to="themes.theme",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_enrichments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentary Enrichment",
                "verbose_name_plural": "Commentary Enrichments",
                "db_table": "commentaries_enrichment",
            },
        ),
        migrations.CreateModel(
            name="VerseComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Whether visible to other authenticated users"),
                ),
                ("is_favorite", models.BooleanField(default=False, help_text="User's favorite/starred comment")),
                ("is_pinned", models.BooleanField(default=False, help_text="Pinned to top of user's comments")),
                ("like_count", models.IntegerField(default=0, help_text="Number of users who marked this helpful")),
                ("reply_count", models.IntegerField(default=0, help_text="Number of replies to this comment")),
                ("view_count", models.IntegerField(default=0, help_text="Number of times viewed (if public)")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reflection", "Personal Reflection"),
                            ("question", "Question"),
                            ("insight", "Theological Insight"),
                            ("study_note", "Study Note"),
                            ("prayer", "Prayer Request"),
                            ("application", "Life Application"),
                            ("cross_reference", "Cross-Reference Note"),
                            ("historical", "Historical Context"),
                            ("linguistic", "Language/Translation Note"),
                        ],
                        help_text="Type of comment",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, help_text="User-defined tags as JSON array")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="commentaries.versecomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verse_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_comments", to="bible.verse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Verse Comment",
                "verbose_name_plural": "Verse Comments",
                "db_table": "commentaries_verse_comment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="vcomm_user_created_idx"),
                    models.Index(fields=["verse", "is_public"], name="vcomm_verse_public_idx"),
                    models.Index(fields=["user", "is_favorite"], name="vcomm_user_favorite_idx"),
                    models.Index(fields=["verse", "category"], name="vcomm_verse_category_idx"),
                    models.Index(fields=["parent_comment"], name="vcomm_parent_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="versecomment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_comment__isnull", True)),
                fields=("verse", "user"),
                name="uniq_verse_user_main_comment",
                violation_error_message="User can only have one main comment per verse",
            ),
        ),
        migrations.AddIndex(
            model_name="commentarytranslation",
            index=models.Index(fields=["entry", "language"], name="commtrans_entry_lang_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarytranslation",
            index=models.Index(fields=["language", "is_reviewed"], name="commtrans_lang_rev_idx"),
        ),
        migrations.AddConstraint(
            model_name="commentarytranslation",
            constraint=models.UniqueConstraint(fields=("entry", "language"), name="uniq_commtrans_entry_lang"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["language", "is_active"], name="commsrc_lang_active_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["short_code"], name="commsrc_short_code_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["source_type", "is_active"], name="commsrc_type_active_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["is_featured"], name="commsrc_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryreference",
            index=models.Index(fields=["source_entry"], name="commref_source_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryreference",
            index=models.Index(fields=["target_entry"], name="commref_target_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryreference",
            index=models.Index(fields=["reference_type"], name="commref_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="commentaryreference",
            constraint=models.UniqueConstraint(
                fields=("source_entry", "target_entry", "reference_type"), name="uniq_commref_src_tgt_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentaryreference",
            constraint=models.CheckConstraint(
                check=models.Q(("source_entry", models.F("target_entry")), _negated=True), name="commref_no_self_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(
                fields=["source", "book", "chapter", "verse_start", "verse_end"], name="commentry_ref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(fields=["book", "chapter"], name="commentry_book_chapter_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(fields=["author"], name="commentry_author_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(fields=["book", "chapter", "is_complete"], name="commentry_complete_idx"),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.UniqueConstraint(
                fields=("source", "author", "book", "chapter", "verse_start", "verse_end"),
                name="uniq_commentry_source_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("verse_end__gte", models.F("verse_start"))), name="commentry_end_gte_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(check=models.Q(("chapter__gte", 1)), name="commentry_chapter_pos"),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("verse_start__gte", 1)), name="commentry_verse_start_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(check=models.Q(("verse_end__gte", 1)), name="commentry_verse_end_pos"),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)),
                name="commentry_confidence_0_1",
            ),
        ),
        migrations.AddIndex(
            model_name="commentaryenrichment",
            index=models.Index(fields=["enrichment_status"], name="commenrich_status_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryenrichment",
            index=models.Index(fields=["is_verified"], name="commenrich_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryenrichment",
            index=models.Index(fields=["theological_method"], name="commenrich_method_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["century"], name="commentarie_century_815016_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["tradition"], name="commentarie_traditi_6236cd_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["birth_year", "death_year"], name="commentarie_birth_y_1c98a3_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["author_type"], name="comm_author_type_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["author_type", "tradition"], name="comm_type_tradition_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["theological_school"], name="comm_theo_school_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["is_saint"], name="comm_is_saint_idx"),
        ),
    ]
