# Generated by Django 4.2.7 on 2026-03-29 20:10

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0022_initial_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=300, unique=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "birth_date",
                    models.CharField(blank=True, help_text="Raw date string (e.g., '1574-05-30')", max_length=30),
                ),
                ("death_date", models.CharField(blank=True, max_length=30)),
                (
                    "nations",
                    models.JSONField(blank=True, default=list, help_text='Artist nationalities (e.g., ["Italians"])'),
                ),
                (
                    "movements",
                    models.JSONField(
                        blank=True, default=list, help_text='Art movements (e.g., ["Baroque", "Renaissance"])'
                    ),
                ),
                (
                    "image_count",
                    models.PositiveIntegerField(default=0, help_text="Denormalized count, updated on import"),
                ),
                ("source", models.CharField(default="wikiart", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "image_artist",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BiblicalImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="WikiArt image key (e.g., '0000004')", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("completion_year", models.IntegerField(blank=True, db_index=True, null=True)),
                ("styles", models.JSONField(blank=True, default=list, help_text='Art styles (e.g., ["Baroque"])')),
                (
                    "genres",
                    models.JSONField(blank=True, default=list, help_text='Genres (e.g., ["religious painting"])'),
                ),
                ("media", models.JSONField(blank=True, default=list, help_text='Media (e.g., ["oil", "canvas"])')),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("image_url", models.URLField(help_text="Full resolution image URL (WikiArt CDN)", max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, help_text="Thumbnail URL (~300px)", max_length=500)),
                ("is_tagged", models.BooleanField(db_index=True, default=False, help_text="Whether AI tags exist")),
                ("source", models.CharField(default="wikiart", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="images.artist"
                    ),
                ),
            ],
            options={
                "db_table": "biblical_image",
                "ordering": ["-completion_year"],
            },
        ),
        migrations.CreateModel(
            name="ImageVerseLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField(help_text="Same as verse_start for single verse")),
                ("relevance_type", models.CharField(help_text="primary, allusion, typological", max_length=30)),
                ("reason", models.TextField(blank=True, help_text="AI explanation for this link")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="bible.canonicalbook",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verse_links",
                        to="images.biblicalimage",
                    ),
                ),
            ],
            options={
                "db_table": "image_verse_link",
            },
        ),
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "characters",
                    models.JSONField(blank=True, default=list, help_text='[{"name": "Moses", "type": "PERSON"}]'),
                ),
                ("event", models.CharField(blank=True, help_text="Biblical event depicted", max_length=500)),
                (
                    "tag_list",
                    models.JSONField(
                        blank=True, default=list, help_text='Free-form tags (e.g., ["martyrdom", "saints"])'
                    ),
                ),
                (
                    "symbols",
                    models.JSONField(
                        blank=True, default=list, help_text='Symbols with meanings (e.g., ["halo — sanctity"])'
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Visual description (~600 chars)")),
                (
                    "theological_description",
                    models.TextField(blank=True, help_text="Deep theological analysis (~1000 chars)"),
                ),
                (
                    "scripture_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Domain truth: [{"ref": "REV.12.11", "relevance": "typological", "reason": "..."}]',
                    ),
                ),
                (
                    "scene_type",
                    models.CharField(blank=True, help_text="narrative, liturgical, symbolic", max_length=50),
                ),
                (
                    "moods",
                    models.JSONField(blank=True, default=list, help_text='Mood tags (e.g., ["anguish", "serenity"])'),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, help_text="Biblical period (Gospel, Pentateuch, etc.)", max_length=100
                    ),
                ),
                (
                    "tagging_model",
                    models.CharField(blank=True, help_text="AI model used (e.g., 'gemini-2.5-flash')", max_length=100),
                ),
                ("tagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tag", to="images.biblicalimage"
                    ),
                ),
            ],
            options={
                "db_table": "image_tag",
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=django.contrib.postgres.indexes.GinIndex(fields=["movements"], name="artist_movements_gin"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=django.contrib.postgres.indexes.GinIndex(fields=["nations"], name="artist_nations_gin"),
        ),
        migrations.AddIndex(
            model_name="imageverselink",
            index=models.Index(fields=["book", "chapter"], name="imgverse_book_ch_idx"),
        ),
        migrations.AddConstraint(
            model_name="imageverselink",
            constraint=models.CheckConstraint(
                check=models.Q(("verse_end__gte", models.F("verse_start"))), name="imgverse_end_gte_start"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="imageverselink",
            unique_together={("image", "book", "chapter", "verse_start")},
        ),
        migrations.AddIndex(
            model_name="imagetag",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tag_list"], name="imgtag_tags_gin"),
        ),
        migrations.AddIndex(
            model_name="imagetag",
            index=django.contrib.postgres.indexes.GinIndex(fields=["characters"], name="imgtag_chars_gin"),
        ),
        migrations.AddIndex(
            model_name="imagetag",
            index=django.contrib.postgres.indexes.GinIndex(fields=["moods"], name="imgtag_moods_gin"),
        ),
        migrations.AddIndex(
            model_name="biblicalimage",
            index=django.contrib.postgres.indexes.GinIndex(fields=["styles"], name="img_styles_gin"),
        ),
        migrations.AddIndex(
            model_name="biblicalimage",
            index=django.contrib.postgres.indexes.GinIndex(fields=["genres"], name="img_genres_gin"),
        ),
        migrations.AddIndex(
            model_name="biblicalimage",
            index=django.contrib.postgres.indexes.GinIndex(fields=["media"], name="img_media_gin"),
        ),
    ]
