# Generated by Django 4.2.7 on 2026-03-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_year",
            field=models.CharField(
                blank=True, help_text="Birth year, approximate allowed (e.g., '354', '~1040 BC')", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="canonical_name",
            field=models.CharField(help_text="Primary display name (e.g., 'Augustine of Hippo')", max_length=200),
        ),
        migrations.AlterField(
            model_name="person",
            name="death_year",
            field=models.CharField(
                blank=True, help_text="Death year, approximate allowed (e.g., '430', '~970 BC')", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, help_text="Brief description (1-2 sentences)"),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("biblical", "Biblical Figure"),
                    ("historical", "Historical Figure"),
                    ("author", "Commentary Author"),
                    ("mixed", "Biblical + Historical Author"),
                ],
                help_text="Primary classification of this person",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier (e.g., 'augustine-of-hippo')", max_length=120, unique=True
            ),
        ),
    ]
