# Generated by Django 4.2.7 on 2025-09-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "themes",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="themes_name_46e88a_idx")],
            },
        ),
        migrations.CreateModel(
            name="CrossReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("parallel", "Parallel"),
                            ("prophecy", "Prophecy"),
                            ("quote", "Quote"),
                            ("theme", "Theme Related"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="crossrefs_from", to="bible.verse"
                    ),
                ),
                (
                    "to_verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="crossrefs_to", to="bible.verse"
                    ),
                ),
            ],
            options={
                "db_table": "cross_references",
                "ordering": ["from_verse_id", "to_verse_id"],
                "indexes": [
                    models.Index(fields=["from_verse"], name="cross_refer_from_ve_71f844_idx"),
                    models.Index(fields=["to_verse"], name="cross_refer_to_vers_4c1d9a_idx"),
                    models.Index(fields=["relationship_type"], name="cross_refer_relatio_d4f67f_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.UniqueConstraint(
                fields=("from_verse", "to_verse", "source"), name="crossref_unique_from_to_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.CheckConstraint(
                check=models.Q(("from_verse", models.F("to_verse")), _negated=True), name="crossref_no_self_reference"
            ),
        ),
    ]
