# Generated by Django 4.2.7 on 2025-09-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0002_theme_crossreference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="color",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="icon",
        ),
        migrations.CreateModel(
            name="VerseTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="verse_links", to="bible.theme"
                    ),
                ),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="theme_links", to="bible.verse"
                    ),
                ),
            ],
            options={
                "db_table": "verse_themes",
                "indexes": [models.Index(fields=["theme"], name="vt_theme_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="versetheme",
            constraint=models.UniqueConstraint(fields=("verse", "theme"), name="uniq_verse_theme"),
        ),
    ]
