# Generated by Django 4.2.7 on 2025-09-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0003_remove_theme_color_remove_theme_icon_versetheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="verses", through="bible.VerseTheme", to="bible.theme"
            ),
        ),
    ]
