# Generated by Django 4.2.7 on 2025-09-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0004_verse_themes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("abbreviation", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "book_names",
                "ordering": ["canonical_book_id", "language_id"],
            },
        ),
        migrations.CreateModel(
            name="CanonicalBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("osis_code", models.CharField(default="Unknown", max_length=12, unique=True)),
                ("canonical_order", models.PositiveIntegerField(default=1, unique=True)),
                ("is_deuterocanonical", models.BooleanField(default=False)),
                ("chapter_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "canonical_books",
                "ordering": ["canonical_order"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Testament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "testaments",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="verse",
            options={"ordering": ["book__canonical_order", "chapter", "number"]},
        ),
        migrations.AlterModelOptions(
            name="version",
            options={"ordering": ["language_id", "code"]},
        ),
        migrations.RemoveIndex(
            model_name="version",
            name="versions_abbrevi_4411a0_idx",
        ),
        migrations.RenameIndex(
            model_name="version",
            new_name="versions_languag_c3e310_idx",
            old_name="versions_languag_38ea4c_idx",
        ),
        migrations.RemoveField(
            model_name="version",
            name="abbreviation",
        ),
        migrations.AddField(
            model_name="version",
            name="code",
            field=models.CharField(db_index=True, default="EN_UNKNOWN", max_length=40),
        ),
        migrations.AddField(
            model_name="version",
            name="copyright",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="permissions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="versification",
            field=models.CharField(default="KJV", max_length=40),
        ),
        migrations.AddIndex(
            model_name="version",
            index=models.Index(fields=["code"], name="versions_code_a432cc_idx"),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(fields=("language", "code"), name="uniq_version_language_code"),
        ),
        migrations.AddField(
            model_name="canonicalbook",
            name="testament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="canonical_books", to="bible.testament"
            ),
        ),
        migrations.AddField(
            model_name="bookname",
            name="canonical_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="names", to="bible.canonicalbook"
            ),
        ),
        migrations.AddField(
            model_name="bookname",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="book_names", to="bible.language"
            ),
        ),
        migrations.AddField(
            model_name="bookname",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_names",
                to="bible.version",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="bible.license",
            ),
        ),
        migrations.AlterField(
            model_name="verse",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="verses", to="bible.canonicalbook"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="language",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="bible.language"
            ),
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AddIndex(
            model_name="canonicalbook",
            index=models.Index(fields=["testament", "canonical_order"], name="canonical_b_testame_a573c2_idx"),
        ),
        migrations.AddIndex(
            model_name="canonicalbook",
            index=models.Index(fields=["osis_code"], name="canonical_b_osis_co_c7b6d3_idx"),
        ),
        migrations.AddConstraint(
            model_name="canonicalbook",
            constraint=models.CheckConstraint(
                check=models.Q(("canonical_order__gte", 1)), name="book_canonical_order_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="bookname",
            index=models.Index(fields=["canonical_book", "language"], name="bookname_book_lang_idx"),
        ),
        migrations.AddIndex(
            model_name="bookname",
            index=models.Index(fields=["abbreviation"], name="book_names_abbrevi_657576_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookname",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__isnull", True)),
                fields=("canonical_book", "language"),
                name="uniq_bookname_lang_when_version_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookname",
            constraint=models.UniqueConstraint(
                condition=models.Q(("version__isnull", False)),
                fields=("canonical_book", "language", "version"),
                name="uniq_bookname_lang_version_when_version_not_null",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bible.canonicalbook",),
        ),
    ]
