# Generated by Django 4.2.7 on 2025-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0006_recreate_crossreferences"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crossreference",
            name="cr_confidence_0_1",
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.CheckConstraint(
                check=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)), name="cr_confidence_0_1"
            ),
        ),
    ]
