# Generated by Django 4.2.7 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0007_remove_crossreference_cr_confidence_0_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalbook",
            name="context_data",
            field=models.JSONField(
                blank=True, help_text="Historical and contextual information for the book", null=True
            ),
        ),
        migrations.AddField(
            model_name="canonicalbook",
            name="outline_data",
            field=models.JSONField(blank=True, help_text="Structured outline data for the book", null=True),
        ),
    ]
