# Generated by Django 4.2.7 on 2025-09-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0009_commentarysource_commentaryentry_versecomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Full canonical name", max_length=200)),
                ("short_name", models.CharField(blank=True, help_text="Common short name or title", max_length=100)),
                ("latin_name", models.CharField(blank=True, help_text="Latin name if applicable", max_length=200)),
                ("hebrew_name", models.CharField(blank=True, help_text="Hebrew name if applicable", max_length=200)),
                ("greek_name", models.CharField(blank=True, help_text="Greek name if applicable", max_length=200)),
                ("also_known_as", models.JSONField(blank=True, default=list, help_text="Alternative names and titles")),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("biblical", "Biblical Author"),
                            ("church_father", "Church Father"),
                            ("medieval", "Medieval Theologian"),
                            ("reformation", "Reformation Era"),
                            ("modern", "Modern Commentator"),
                            ("contemporary", "Contemporary Scholar"),
                            ("legendary", "Traditional/Legendary"),
                        ],
                        help_text="Primary category of author",
                        max_length=30,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(blank=True, help_text="More specific categorization", max_length=100),
                ),
                ("birth_year", models.IntegerField(blank=True, help_text="Approximate birth year", null=True)),
                ("death_year", models.IntegerField(blank=True, help_text="Approximate death year", null=True)),
                (
                    "century",
                    models.CharField(blank=True, help_text="Primary century (e.g., '4th century')", max_length=50),
                ),
                ("period", models.CharField(blank=True, help_text="Historical period description", max_length=100)),
                ("birthplace", models.CharField(blank=True, max_length=200)),
                (
                    "primary_location",
                    models.CharField(blank=True, help_text="Where they primarily worked/taught", max_length=200),
                ),
                ("cultural_context", models.TextField(blank=True, help_text="Cultural and political context")),
                (
                    "tradition",
                    models.CharField(blank=True, help_text="Eastern/Western, Orthodox/Catholic/etc", max_length=100),
                ),
                (
                    "theological_school",
                    models.CharField(blank=True, help_text="Antiochene, Alexandrian, etc", max_length=200),
                ),
                (
                    "ecclesiastical_rank",
                    models.CharField(blank=True, help_text="Bishop, Presbyter, Monk, etc", max_length=100),
                ),
                ("feast_day", models.CharField(blank=True, help_text="Liturgical feast day if saint", max_length=50)),
                (
                    "biblical_role",
                    models.CharField(
                        blank=True,
                        help_text="Role in biblical narrative (prophet, apostle, king, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "biblical_period",
                    models.CharField(
                        blank=True, help_text="Biblical historical period (United Kingdom, Exile, etc.)", max_length=100
                    ),
                ),
                ("specializations", models.JSONField(blank=True, default=list, help_text="Areas of expertise")),
                (
                    "major_works",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of major works (biblical books, theological works, etc.)",
                    ),
                ),
                ("modern_significance", models.TextField(blank=True, help_text="Why this author matters today")),
                ("scholarly_consensus", models.TextField(blank=True, help_text="Current academic view of their work")),
                ("biography_summary", models.TextField(blank=True, help_text="Concise biographical summary")),
                ("theological_contributions", models.TextField(blank=True, help_text="Key theological contributions")),
                ("historical_impact", models.TextField(blank=True, help_text="Impact on church history")),
                (
                    "reliability_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent - Well documented"),
                            ("good", "Good - Generally reliable"),
                            ("fair", "Fair - Some uncertainty"),
                            ("poor", "Poor - Limited information"),
                            ("legendary", "Legendary - Mostly traditional"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("portrait_image", models.URLField(blank=True, help_text="URL to author's portrait/icon")),
                (
                    "portrait_description",
                    models.CharField(blank=True, help_text="Alt text for portrait", max_length=300),
                ),
                (
                    "portrait_source",
                    models.CharField(blank=True, help_text="Source/attribution for image", max_length=200),
                ),
                (
                    "portrait_license",
                    models.CharField(blank=True, help_text="Image license (CC, Public Domain, etc)", max_length=100),
                ),
                (
                    "episcopal_appointment",
                    models.IntegerField(blank=True, help_text="Year of episcopal appointment", null=True),
                ),
                (
                    "presbyterial_appointment",
                    models.IntegerField(blank=True, help_text="Year of presbyterial appointment", null=True),
                ),
                ("papal_election", models.IntegerField(blank=True, help_text="Year of papal election", null=True)),
                (
                    "historical_sources",
                    models.JSONField(blank=True, default=list, help_text="Historical sources and editions"),
                ),
                ("wikipedia_url", models.URLField(blank=True)),
                ("external_links", models.JSONField(blank=True, default=list, help_text="Additional reference links")),
                ("bibliography", models.TextField(blank=True, help_text="Key academic sources")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biblical_books_authored",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Books traditionally attributed to this author",
                        related_name="traditional_authors",
                        to="bible.canonicalbook",
                    ),
                ),
                ("contemporary_with", models.ManyToManyField(blank=True, to="bible.author")),
                ("influenced_by", models.ManyToManyField(blank=True, related_name="influenced", to="bible.author")),
                (
                    "primary_language",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bible.language"
                    ),
                ),
            ],
            options={
                "db_table": "commentary_authors",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["century"], name="commentary__century_68e589_idx"),
                    models.Index(fields=["tradition"], name="commentary__traditi_5e59a7_idx"),
                    models.Index(fields=["birth_year", "death_year"], name="commentary__birth_y_0e27d3_idx"),
                ],
            },
        ),
    ]
