# Generated by Django 4.2.7 on 2025-09-14 02:38

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


def create_vector_extension(apps, schema_editor):
    """Create vector extension if available, skip if not."""
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector")
    except Exception:
        # Skip if extension is not available (e.g., in CI)
        pass


def reverse_vector_extension(apps, schema_editor):
    """No-op reverse operation."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0010_author"),
    ]

    operations = [
        migrations.RunPython(
            code=create_vector_extension,
            reverse_code=reverse_vector_extension,
        ),
        migrations.CreateModel(
            name="VerseEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_code", models.CharField(db_index=True, max_length=40)),
                ("model_name_small", models.CharField(max_length=80)),
                ("dim_small", models.PositiveIntegerField()),
                ("embedding_small", pgvector.django.VectorField(null=True)),
                ("model_name_large", models.CharField(blank=True, max_length=80, null=True)),
                ("dim_large", models.PositiveIntegerField(blank=True, null=True)),
                ("embedding_large", pgvector.django.VectorField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verse",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="embedding", to="bible.verse"
                    ),
                ),
            ],
            options={
                "db_table": "verse_embeddings",
                "indexes": [models.Index(fields=["version_code"], name="verse_embed_version_209acc_idx")],
            },
        ),
    ]
