# Generated by Django 4.2.7 on 2025-09-14 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0012_vector_indexes"),
    ]

    operations = [
        migrations.RunSQL(sql="SELECT 1", reverse_sql="SELECT 1"),
    ]
