# Generated by Django 4.2.7 on 2025-09-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0013_set_vector_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookname",
            name="abbreviation",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="commentaryentry",
            name="body_html",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="commentarysource",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="explanation",
            field=models.TextField(blank=True, default="", help_text="Nota explicativa sobre a referência"),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="source",
            field=models.CharField(blank=True, default="", help_text="Ex: TSK, OpenBible", max_length=120),
        ),
        migrations.AlterField(
            model_name="license",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="testament",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="testament",
            name="name",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="verseembedding",
            name="model_name_large",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="version",
            name="copyright",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="version",
            name="permissions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="version",
            name="source_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
