# Generated by Django 4.2.7 on 2025-11-16 17:02

import django.contrib.postgres.fields
from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0014_alter_bookname_abbreviation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedVerseEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "canonical_verse_id",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical reference like 'Gn.1.1', 'Mt.5.3'",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "source_versions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        help_text="List of version codes used in fusion: ['NAA', 'ARA', 'NVI']",
                        size=None,
                    ),
                ),
                (
                    "version_weights",
                    models.JSONField(help_text="Weights used in fusion: {'NAA': 0.4, 'ARA': 0.35, 'NVI': 0.25}"),
                ),
                ("model_name_small", models.CharField(default="text-embedding-3-small", max_length=80)),
                ("dim_small", models.PositiveIntegerField(default=1536)),
                (
                    "unified_embedding_small",
                    pgvector.django.VectorField(
                        blank=True, dimensions=1536, help_text="Unified small embedding for fast recall", null=True
                    ),
                ),
                ("model_name_large", models.CharField(blank=True, default="text-embedding-3-large", max_length=80)),
                ("dim_large", models.PositiveIntegerField(blank=True, default=3072, null=True)),
                (
                    "unified_embedding_large",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=3072,
                        help_text="Unified large embedding for precise reranking",
                        null=True,
                    ),
                ),
                (
                    "fusion_strategy",
                    models.CharField(
                        default="weighted_average",
                        help_text="Strategy used: weighted_average, max_pooling, concatenation",
                        max_length=30,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, help_text="Quality score of the unified embedding (0.0-1.0)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "unified_verse_embeddings",
                "indexes": [
                    models.Index(fields=["canonical_verse_id"], name="unified_ver_canonic_538863_idx"),
                    models.Index(fields=["quality_score"], name="unified_ver_quality_e197b6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnifiedThemeEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique theme identifier like 'graça_divina', 'amor_de_deus'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("theme_text", models.TextField(help_text="Human-readable theme text: 'Graça divina', 'Amor de Deus'")),
                (
                    "source_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        help_text="List of topic IDs that contributed to this theme: ['GOD', 'GRACE']",
                        size=None,
                    ),
                ),
                ("model_name_small", models.CharField(default="text-embedding-3-small", max_length=80)),
                ("dim_small", models.PositiveIntegerField(default=1536)),
                (
                    "unified_embedding_small",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Unified small embedding for fast theme discovery",
                        null=True,
                    ),
                ),
                ("model_name_large", models.CharField(default="text-embedding-3-large", max_length=80)),
                ("dim_large", models.PositiveIntegerField(default=3072)),
                (
                    "unified_embedding_large",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=3072,
                        help_text="Unified large embedding for precise semantic scoring",
                        null=True,
                    ),
                ),
                (
                    "fusion_strategy",
                    models.CharField(
                        default="weighted_average",
                        help_text="Strategy used for combining topic embeddings",
                        max_length=30,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(default=0.0, help_text="Quality score of the unified theme embedding (0.0-1.0)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "unified_theme_embeddings",
                "indexes": [
                    models.Index(fields=["theme_id"], name="unified_the_theme_i_5137a0_idx"),
                    models.Index(fields=["quality_score"], name="unified_the_quality_d7acc7_idx"),
                ],
            },
        ),
    ]
