# Generated by Django 4.2.7 on 2025-11-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0015_unifiedverseembedding_unifiedthemeembedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testament",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="testament",
            name="abbreviation",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="testament",
            name="description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testament",
            name="description_es",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="testament",
            name="display_name",
            field=models.CharField(
                blank=True, default="", help_text="Nome para exibição (ex: 'Antigo Testamento')", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="testament",
            name="display_name_en",
            field=models.CharField(blank=True, default="", help_text="Nome em inglês para exibição", max_length=100),
        ),
        migrations.AddField(
            model_name="testament",
            name="display_name_es",
            field=models.CharField(blank=True, default="", help_text="Nome em espanhol para exibição", max_length=100),
        ),
        migrations.AddField(
            model_name="testament",
            name="order",
            field=models.IntegerField(default=0, help_text="Ordem de exibição (1=Antigo, 2=Novo)"),
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("name_pt", models.CharField(blank=True, default="", max_length=100)),
                ("name_en", models.CharField(blank=True, default="", max_length=100)),
                ("name_es", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("description_pt", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                ("description_es", models.TextField(blank=True, default="")),
                ("order", models.IntegerField(default=0, help_text="Ordem dentro do testamento")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "testament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="bible.testament"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Category",
                "verbose_name_plural": "Book Categories",
                "db_table": "book_categories",
                "ordering": ["testament", "order"],
                "unique_together": {("testament", "name")},
            },
        ),
        migrations.AddField(
            model_name="canonicalbook",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="bible.bookcategory",
            ),
        ),
    ]
