# Generated by Django 4.2.7 on 2025-11-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0016_alter_testament_options_testament_abbreviation_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="commentarysource",
            new_name="cs_lang_active_idx",
            old_name="commentary__languag_ea0093_idx",
        ),
        migrations.RenameIndex(
            model_name="commentarysource",
            new_name="cs_short_code_idx",
            old_name="commentary__short_c_b00d08_idx",
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="ai_summary",
            field=models.JSONField(blank=True, default=dict, help_text="AI generated summary"),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="argumentative_structure",
            field=models.JSONField(blank=True, default=dict, help_text="Thesis, arguments, conclusion"),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary_entries",
                to="bible.author",
            ),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="confidence_score",
            field=models.FloatField(blank=True, help_text="Data quality/accuracy score (0.0-1.0)", null=True),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="is_complete",
            field=models.BooleanField(default=True, help_text="Whether this entry is complete (vs. excerpt/summary)"),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="original_language",
            field=models.CharField(
                blank=True, help_text="Original language of text (e.g., 'Latin', 'Greek', 'English')", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="spiritual_insight",
            field=models.JSONField(blank=True, default=dict, help_text="Themes and practical reflection"),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="theological_analysis",
            field=models.JSONField(blank=True, default=dict, help_text="Doctrines, traditions, method"),
        ),
        migrations.AddField(
            model_name="commentaryentry",
            name="word_count",
            field=models.IntegerField(blank=True, help_text="Approximate word count for length indication", null=True),
        ),
        migrations.AddField(
            model_name="commentarysource",
            name="author_type",
            field=models.CharField(
                blank=True, help_text="Type of authors (e.g., 'Medieval', 'Reformation', 'Modern')", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="commentarysource",
            name="cover_image_url",
            field=models.URLField(blank=True, help_text="URL to cover image/icon for UI display"),
        ),
        migrations.AddField(
            model_name="commentarysource",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Whether to feature prominently in UI"),
        ),
        migrations.AddField(
            model_name="commentarysource",
            name="publication_year",
            field=models.IntegerField(blank=True, help_text="Year of publication or primary edition", null=True),
        ),
        migrations.AddField(
            model_name="versecomment",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reflection", "Personal Reflection"),
                    ("question", "Question"),
                    ("insight", "Theological Insight"),
                    ("study_note", "Study Note"),
                    ("prayer", "Prayer Request"),
                ],
                help_text="Type of comment",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="versecomment",
            name="like_count",
            field=models.IntegerField(default=0, help_text="Number of users who marked this helpful"),
        ),
        migrations.AddField(
            model_name="versecomment",
            name="reply_count",
            field=models.IntegerField(default=0, help_text="Number of replies to this comment"),
        ),
        migrations.AlterField(
            model_name="commentarysource",
            name="name",
            field=models.CharField(
                help_text="Full name of the commentary source (e.g., 'Matthew Henry Complete Commentary')",
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="commentarysource",
            name="short_code",
            field=models.CharField(
                help_text="Unique identifier (e.g., 'MHCC', 'TSK', 'BARNES')", max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="versecomment",
            name="is_public",
            field=models.BooleanField(default=False, help_text="Whether visible to other authenticated users"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["author_type"], name="author_type_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["author_type", "tradition"], name="author_type_tradition_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(fields=["author"], name="commentary_author_idx"),
        ),
        migrations.AddIndex(
            model_name="commentaryentry",
            index=models.Index(fields=["book", "chapter", "is_complete"], name="commentary_complete_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["author_type", "is_active"], name="cs_type_active_idx"),
        ),
        migrations.AddIndex(
            model_name="commentarysource",
            index=models.Index(fields=["is_featured"], name="cs_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="versecomment",
            index=models.Index(fields=["verse", "category"], name="vcomment_verse_category_idx"),
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.CheckConstraint(
                check=models.Q(("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)),
                name="commentary_confidence_0_1",
            ),
        ),
    ]
