# Generated by Django 4.2.7 on 2025-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0017_rename_commentary__languag_ea0093_idx_cs_lang_active_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="commentaryentry",
            name="uniq_commentary_source_ref",
        ),
        migrations.AddConstraint(
            model_name="commentaryentry",
            constraint=models.UniqueConstraint(
                fields=("source", "author", "book", "chapter", "verse_start", "verse_end"),
                name="uniq_commentary_source_ref",
            ),
        ),
    ]
