# Generated by Django 4.2.7 on 2025-11-29 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0018_remove_commentaryentry_uniq_commentary_source_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryExpansionCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "query_normalized",
                    models.CharField(
                        db_index=True,
                        help_text="Query normalizada (lowercase) para lookup rápido",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "query_original",
                    models.CharField(help_text="Query original como digitada pelo usuário", max_length=255),
                ),
                (
                    "theological_synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Sinônimos teológicos: termos com significado similar no contexto bíblico",
                        size=None,
                    ),
                ),
                (
                    "morphological_variants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Variações morfológicas: diferentes formas da mesma palavra",
                        size=None,
                    ),
                ),
                (
                    "related_concepts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Conceitos relacionados: termos que frequentemente aparecem juntos",
                        size=None,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini", help_text="Modelo LLM usado para gerar a expansão", max_length=50
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="v1", help_text="Versão do prompt usado para gerar a expansão", max_length=20
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=1.0, help_text="Score de confiança da expansão (0.0-1.0)"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, help_text="Quantidade de vezes que esta expansão foi usada"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="Última vez que esta expansão foi usada", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Query Expansion Cache",
                "verbose_name_plural": "Query Expansion Cache",
                "db_table": "query_expansion_cache",
                "indexes": [
                    models.Index(fields=["query_normalized"], name="query_expan_query_n_5dd352_idx"),
                    models.Index(fields=["usage_count"], name="query_expan_usage_c_9cc80e_idx"),
                    models.Index(fields=["created_at"], name="query_expan_created_463929_idx"),
                ],
            },
        ),
    ]
