# Generated by Django 4.2.7 on 2025-11-30 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0019_add_query_expansion_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryNLPCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "query_normalized",
                    models.CharField(
                        db_index=True, help_text="Query normalizada para lookup rápido", max_length=500, unique=True
                    ),
                ),
                (
                    "query_original",
                    models.CharField(help_text="Query original como digitada pelo usuário", max_length=500),
                ),
                (
                    "semantic_type",
                    models.CharField(
                        choices=[
                            ("phrase", "Frase exata"),
                            ("concept", "Conceito abstrato"),
                            ("reference", "Referência bíblica"),
                            ("entity", "Entidade (pessoa, lugar, etc.)"),
                            ("keyword", "Palavra-chave única"),
                            ("question", "Pergunta"),
                        ],
                        help_text="Tipo semântico da query",
                        max_length=50,
                    ),
                ),
                (
                    "semantic_confidence",
                    models.FloatField(default=0.0, help_text="Confiança na classificação semântica (0.0-1.0)"),
                ),
                (
                    "tokens_raw",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Tokens brutos da query",
                        size=None,
                    ),
                ),
                (
                    "tokens_clean",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Tokens após remoção de stopwords",
                        size=None,
                    ),
                ),
                (
                    "tokens_lemma",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Lemas dos tokens",
                        size=None,
                    ),
                ),
                (
                    "stopwords_removed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="Stopwords removidas da query",
                        size=None,
                    ),
                ),
                ("entities", models.JSONField(default=list, help_text="Entidades detectadas via Gazetteer")),
                (
                    "boost_strategy",
                    models.JSONField(
                        default=dict, help_text="Estratégia de boost calculada (alpha, expand, entity_boost, etc.)"
                    ),
                ),
                (
                    "tsquery_optimized",
                    models.CharField(
                        blank=True, default="", help_text="TSQuery otimizado com distância dinâmica", max_length=1000
                    ),
                ),
                (
                    "bigrams",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Bigramas da query",
                        size=None,
                    ),
                ),
                (
                    "trigrams",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150),
                        default=list,
                        help_text="Trigramas da query",
                        size=None,
                    ),
                ),
                (
                    "is_known_phrase",
                    models.BooleanField(default=False, help_text="Se a query é uma frase conhecida/comum"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, help_text="Quantidade de vezes que esta análise foi usada"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="Última vez que esta análise foi usada", null=True),
                ),
                (
                    "processing_time_ms",
                    models.FloatField(default=0.0, help_text="Tempo de processamento original em ms"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Query NLP Cache",
                "verbose_name_plural": "Query NLP Cache",
                "db_table": "query_nlp_cache",
                "indexes": [
                    models.Index(fields=["query_normalized"], name="query_nlp_c_query_n_06445f_idx"),
                    models.Index(fields=["semantic_type"], name="query_nlp_c_semanti_6c64bc_idx"),
                    models.Index(fields=["usage_count"], name="query_nlp_c_usage_c_d71ef1_idx"),
                    models.Index(fields=["created_at"], name="query_nlp_c_created_81fae7_idx"),
                ],
            },
        ),
    ]
