# Generated by Django 4.2.7 on 2025-12-06 16:10

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0020_add_query_nlp_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("canonical_id", models.CharField(max_length=100, unique=True)),
                ("canonical_name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(db_index=True, max_length=200)),
                (
                    "topic_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("place", "Place"),
                            ("concept", "Concept"),
                            ("event", "Event"),
                            ("object", "Object"),
                            ("literary", "Literary Term"),
                        ],
                        db_index=True,
                        default="concept",
                        max_length=20,
                    ),
                ),
                ("primary_source", models.CharField(max_length=10)),
                (
                    "available_sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), blank=True, default=list, size=None
                    ),
                ),
                ("total_verses", models.IntegerField(default=0)),
                ("ot_refs", models.IntegerField(default=0)),
                ("nt_refs", models.IntegerField(default=0)),
                ("books_count", models.IntegerField(default=0)),
                ("aspects_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("ai_enriched", models.BooleanField(default=False)),
                ("ai_model", models.CharField(blank=True, max_length=50)),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("ai_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("ai_run_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("quality_score", models.FloatField(default=0.0)),
                ("needs_review", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topics",
                "ordering": ["name_normalized"],
            },
        ),
        migrations.CreateModel(
            name="TopicAspect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("canonical_label", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=150)),
                ("order", models.IntegerField(default=0)),
                (
                    "raw_references",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), blank=True, default=list, size=None
                    ),
                ),
                ("verse_count", models.IntegerField(default=0)),
                ("ot_refs", models.IntegerField(default=0)),
                ("nt_refs", models.IntegerField(default=0)),
                (
                    "books",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20), blank=True, default=list, size=None
                    ),
                ),
                ("source", models.CharField(default="NAV", max_length=10)),
            ],
            options={
                "db_table": "topic_aspects",
                "ordering": ["topic", "order"],
            },
        ),
        migrations.CreateModel(
            name="TopicAspectLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_aspect_labels",
            },
        ),
        migrations.CreateModel(
            name="TopicContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField(blank=True)),
                (
                    "outline",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "key_concepts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), blank=True, default=list, size=None
                    ),
                ),
                ("theological_significance", models.TextField(blank=True)),
                ("primary_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_contents",
            },
        ),
        migrations.CreateModel(
            name="TopicCrossReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relevance_score",
                    models.FloatField(
                        default=1.0, help_text="How relevant this cross-reference is to this specific topic (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topic_cross_references",
            },
        ),
        migrations.CreateModel(
            name="TopicDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("EAS", "Easton's Bible Dictionary"),
                            ("SMI", "Smith's Bible Dictionary"),
                            ("NAV", "Nave's Topical Bible"),
                            ("TOR", "Torrey's Topical Textbook"),
                            ("ATS", "American Tract Society Dictionary"),
                            ("ISB", "International Standard Bible Encyclopedia"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("text", models.TextField()),
                ("text_length", models.IntegerField(default=0)),
                ("extracted_refs", models.JSONField(default=list)),
                ("refs_count", models.IntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_definitions",
                "ordering": ["topic", "source"],
            },
        ),
        migrations.CreateModel(
            name="TopicName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), blank=True, default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_names",
                "ordering": ["topic", "language"],
            },
        ),
        migrations.CreateModel(
            name="TopicPipelineMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase0_processed_at", models.DateTimeField(blank=True, null=True)),
                ("phase0_run_id", models.CharField(blank=True, max_length=100)),
                ("phase1_processed_at", models.DateTimeField(blank=True, null=True)),
                ("phase1_summary", models.JSONField(blank=True, default=dict)),
                ("phase1_results", models.JSONField(blank=True, default=list)),
                ("phase2_processed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_json_backup", models.BinaryField(blank=True, null=True)),
                ("pipeline_version", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_pipeline_metadata",
            },
        ),
        migrations.CreateModel(
            name="TopicRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("see_also", "See Also"),
                            ("related", "Related"),
                            ("parent", "Parent Topic"),
                            ("child", "Child Topic"),
                            ("alias", "Alias"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topic_relations",
            },
        ),
        migrations.CreateModel(
            name="TopicThemeLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proposal_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("label_original", models.CharField(max_length=300)),
                ("label_en", models.CharField(max_length=300)),
                ("label_normalized", models.CharField(db_index=True, max_length=200)),
                (
                    "anchor_verses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Key verses that anchor this theme, e.g., ['Genesis 12:1', 'Hebrews 11:8']",
                        size=None,
                    ),
                ),
                (
                    "anchor_source",
                    models.CharField(
                        choices=[
                            ("ai_trusted", "AI Trusted"),
                            ("ai_fallback", "AI Fallback"),
                            ("manual", "Manual/Curated"),
                            ("derived", "Derived from Data"),
                        ],
                        default="ai_trusted",
                        max_length=20,
                    ),
                ),
                (
                    "anchor_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata about anchor selection: ai_suggested, validated, fallback_used",
                    ),
                ),
                (
                    "semantic_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Keywords for semantic search: ['faith', 'obedience', 'trust']",
                        size=None,
                    ),
                ),
                (
                    "theological_domain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("theology_proper", "Theology Proper (God)"),
                            ("christology", "Christology (Christ)"),
                            ("pneumatology", "Pneumatology (Holy Spirit)"),
                            ("anthropology", "Anthropology (Humanity)"),
                            ("hamartiology", "Hamartiology (Sin)"),
                            ("soteriology", "Soteriology (Salvation)"),
                            ("ecclesiology", "Ecclesiology (Church)"),
                            ("eschatology", "Eschatology (End Times)"),
                            ("bibliology", "Bibliology (Scripture)"),
                            ("angelology", "Angelology (Angels/Demons)"),
                            ("ethics", "Ethics/Morality"),
                            ("worship", "Worship/Liturgy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("aspect", models.TextField(blank=True)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=1.0)),
                ("source", models.CharField(default="ai_enrichment", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topic_theme_links",
            },
        ),
        migrations.CreateModel(
            name="TopicVerse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relevance_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topic_verses",
            },
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_enriched",
            field=models.BooleanField(db_index=True, default=False, help_text="Se foi enriquecido por IA"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_enriched_at",
            field=models.DateTimeField(blank=True, help_text="Quando foi enriquecido por IA", null=True),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_explanation",
            field=models.TextField(blank=True, help_text="Explicação detalhada gerada por IA (inglês)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_explanation_pt",
            field=models.TextField(blank=True, help_text="Explicação detalhada gerada por IA (português)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_model",
            field=models.CharField(blank=True, help_text="Modelo usado para enriquecimento", max_length=50),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="ai_run_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="ID do batch de processamento AI", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="bookmark_count",
            field=models.PositiveIntegerField(default=0, help_text="Número de vezes que foi salvo/favoritado"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("scholarly", "Scholarly"),
                ],
                default="intermediate",
                help_text="Nível de dificuldade para compreensão",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ot_ot", "Old Testament → Old Testament"),
                    ("ot_nt", "Old Testament → New Testament"),
                    ("nt_ot", "New Testament → Old Testament"),
                    ("nt_nt", "New Testament → New Testament"),
                ],
                db_index=True,
                help_text="Direção canônica (AT→NT, NT→AT, etc.)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="discovery_potential",
            field=models.FloatField(
                default=0.0, help_text="Quão 'surpreendente' ou insight-geradora é esta conexão (0-10)"
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="genre_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("narrative", "Narrative"),
                    ("law", "Law/Torah"),
                    ("poetry", "Poetry"),
                    ("wisdom", "Wisdom Literature"),
                    ("prophecy", "Prophecy"),
                    ("apocalyptic", "Apocalyptic"),
                    ("gospel", "Gospel"),
                    ("epistle", "Epistle"),
                    ("parable", "Parable"),
                    ("psalm", "Psalm"),
                    ("proverb", "Proverb"),
                ],
                help_text="Gênero literário do versículo de origem",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="genre_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("narrative", "Narrative"),
                    ("law", "Law/Torah"),
                    ("poetry", "Poetry"),
                    ("wisdom", "Wisdom Literature"),
                    ("prophecy", "Prophecy"),
                    ("apocalyptic", "Apocalyptic"),
                    ("gospel", "Gospel"),
                    ("epistle", "Epistle"),
                    ("parable", "Parable"),
                    ("psalm", "Psalm"),
                    ("proverb", "Proverb"),
                ],
                help_text="Gênero literário do versículo de destino",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="hermeneutical_notes",
            field=models.TextField(blank=True, help_text="Notas sobre princípios hermenêuticos aplicáveis"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="linguistic_similarity",
            field=models.FloatField(default=0.0, help_text="Similaridade textual calculada (0-1)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("direct_quote", "Direct Quote"),
                    ("paraphrase", "Paraphrase"),
                    ("allusion", "Allusion"),
                    ("echo", "Echo"),
                    ("parallel", "Parallel Passage"),
                    ("synoptic", "Synoptic Parallel"),
                    ("duplicate", "Duplicate Account"),
                    ("prophecy", "Prophecy-Fulfillment"),
                    ("typology", "Typology"),
                    ("foreshadow", "Foreshadowing"),
                    ("thematic", "Thematic Connection"),
                    ("theological", "Theological Link"),
                    ("contrast", "Contrast"),
                    ("expansion", "Expansion"),
                    ("illustration", "Illustration"),
                    ("historical", "Historical Reference"),
                    ("genealogical", "Genealogical"),
                    ("geographical", "Geographical"),
                    ("wordplay", "Wordplay/Pun"),
                    ("intertextual", "Intertextual"),
                    ("unclassified", "Unclassified"),
                ],
                db_index=True,
                default="unclassified",
                help_text="Tipo de relação entre os versículos",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="same_author",
            field=models.BooleanField(default=False, help_text="Mesmo autor tradicional (Paulo→Paulo, Moisés→Moisés)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="semantic_similarity",
            field=models.FloatField(default=0.0, help_text="Similaridade semântica via embeddings (0-1)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="shared_keywords_greek",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Palavras-chave gregas em comum",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="shared_keywords_hebrew",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Palavras-chave hebraicas em comum",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="shared_themes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Temas compartilhados: ['redemption', 'covenant', 'faith']",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="strength",
            field=models.CharField(
                choices=[
                    ("certain", "Certain"),
                    ("strong", "Strong"),
                    ("moderate", "Moderate"),
                    ("weak", "Weak"),
                    ("speculative", "Speculative"),
                ],
                default="moderate",
                help_text="Força/certeza da conexão",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="study_value",
            field=models.FloatField(default=0.0, help_text="Valor para estudo bíblico (0-10)"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="theological_significance",
            field=models.TextField(blank=True, help_text="Significado teológico desta conexão"),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="crossreference",
            name="view_count",
            field=models.PositiveIntegerField(default=0, help_text="Número de visualizações"),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="explanation",
            field=models.TextField(
                blank=True, default="", help_text="Explicação da referência (fonte original ou curada)"
            ),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="from_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="xrefs_from", to="bible.canonicalbook"
            ),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Fonte: TSK, OpenBible, Nestle-Aland, etc.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="to_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="xrefs_to", to="bible.canonicalbook"
            ),
        ),
        migrations.AlterField(
            model_name="crossreference",
            name="votes",
            field=models.PositiveIntegerField(default=0, help_text="Votos de relevância (crowdsourced)"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["relation_type"], name="cr_relation_type_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["direction"], name="cr_direction_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["strength"], name="cr_strength_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["ai_enriched"], name="cr_ai_enriched_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["study_value"], name="cr_study_value_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["difficulty_level"], name="cr_difficulty_idx"),
        ),
        migrations.AddIndex(
            model_name="crossreference",
            index=models.Index(fields=["relation_type", "ai_enriched"], name="cr_type_enriched_idx"),
        ),
        migrations.AddConstraint(
            model_name="crossreference",
            constraint=models.CheckConstraint(
                check=models.Q(("study_value__gte", 0.0), ("study_value__lte", 10.0)), name="cr_study_value_0_10"
            ),
        ),
        migrations.AddField(
            model_name="topicverse",
            name="aspect",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="bible.topicaspect"
            ),
        ),
        migrations.AddField(
            model_name="topicverse",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="verse_links", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicverse",
            name="verse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="topic_links", to="bible.verse"
            ),
        ),
        migrations.AddField(
            model_name="topicthemelink",
            name="parent_theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_topic_links",
                to="bible.theme",
            ),
        ),
        migrations.AddField(
            model_name="topicthemelink",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="topic_sources", to="bible.theme"
            ),
        ),
        migrations.AddField(
            model_name="topicthemelink",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="theme_links", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicrelation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_relations", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicrelation",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="incoming_relations", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicpipelinemetadata",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="pipeline_metadata", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicname",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="topic_names", to="bible.language"
            ),
        ),
        migrations.AddField(
            model_name="topicname",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="names", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicdefinition",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="definitions", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topiccrossreference",
            name="aspect",
            field=models.ForeignKey(
                blank=True,
                help_text="Which aspect/subtopic this cross-reference relates to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cross_references",
                to="bible.topicaspect",
            ),
        ),
        migrations.AddField(
            model_name="topiccrossreference",
            name="cross_reference",
            field=models.ForeignKey(
                help_text="Link to the canonical cross-reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_links",
                to="bible.crossreference",
            ),
        ),
        migrations.AddField(
            model_name="topiccrossreference",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cross_references", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topiccontent",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="topic_contents", to="bible.language"
            ),
        ),
        migrations.AddField(
            model_name="topiccontent",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="bible.topic"
            ),
        ),
        migrations.AddField(
            model_name="topicaspectlabel",
            name="aspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="labels", to="bible.topicaspect"
            ),
        ),
        migrations.AddField(
            model_name="topicaspectlabel",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="aspect_labels", to="bible.language"
            ),
        ),
        migrations.AddField(
            model_name="topicaspect",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="aspects", to="bible.topic"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["name_normalized"], name="topics_name_no_619951_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["primary_source"], name="topics_primary_042eb0_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["ai_enriched"], name="topics_ai_enri_d072b8_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["topic_type"], name="topics_topic_t_2fb27c_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["quality_score"], name="topics_quality_e11130_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["topic_type", "ai_enriched"], name="topic_type_enriched_idx"),
        ),
        migrations.AddIndex(
            model_name="topicverse",
            index=models.Index(fields=["topic"], name="topic_verse_topic_i_4a6b37_idx"),
        ),
        migrations.AddIndex(
            model_name="topicverse",
            index=models.Index(fields=["verse"], name="topic_verse_verse_i_2e6d87_idx"),
        ),
        migrations.AddConstraint(
            model_name="topicverse",
            constraint=models.UniqueConstraint(fields=("topic", "verse"), name="uniq_topic_verse"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=models.Index(fields=["topic"], name="topic_theme_topic_i_abe5b7_idx"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=models.Index(fields=["theme"], name="topic_theme_theme_i_6a62df_idx"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=models.Index(fields=["label_normalized"], name="topic_theme_label_n_9ed2d4_idx"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=models.Index(fields=["theological_domain"], name="topic_theme_theolog_48720d_idx"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=models.Index(fields=["relevance_score"], name="topic_theme_relevan_a58771_idx"),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["semantic_keywords"], name="topictheme_keywords_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="topicthemelink",
            index=django.contrib.postgres.indexes.GinIndex(fields=["anchor_verses"], name="topictheme_anchors_gin"),
        ),
        migrations.AddConstraint(
            model_name="topicthemelink",
            constraint=models.UniqueConstraint(fields=("topic", "theme"), name="uniq_topic_theme_link"),
        ),
        migrations.AddConstraint(
            model_name="topicrelation",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relation_type"), name="uniq_topic_relation"
            ),
        ),
        migrations.AddIndex(
            model_name="topicname",
            index=models.Index(fields=["topic", "language"], name="topicname_topic_lang_idx"),
        ),
        migrations.AddIndex(
            model_name="topicname",
            index=models.Index(fields=["name"], name="topic_names_name_f73944_idx"),
        ),
        migrations.AddIndex(
            model_name="topicname",
            index=django.contrib.postgres.indexes.GinIndex(fields=["aliases"], name="topicname_aliases_gin"),
        ),
        migrations.AddConstraint(
            model_name="topicname",
            constraint=models.UniqueConstraint(fields=("topic", "language"), name="uniq_topic_name_per_language"),
        ),
        migrations.AddIndex(
            model_name="topicdefinition",
            index=models.Index(fields=["source"], name="topic_defin_source_0713d8_idx"),
        ),
        migrations.AddIndex(
            model_name="topicdefinition",
            index=models.Index(fields=["refs_count"], name="topic_defin_refs_co_5860fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="topicdefinition",
            constraint=models.UniqueConstraint(fields=("topic", "source"), name="uniq_topic_definition_source"),
        ),
        migrations.AddIndex(
            model_name="topiccrossreference",
            index=models.Index(fields=["topic"], name="topic_cross_topic_i_d8841a_idx"),
        ),
        migrations.AddIndex(
            model_name="topiccrossreference",
            index=models.Index(fields=["cross_reference"], name="topic_cross_cross_r_bdd5bd_idx"),
        ),
        migrations.AddIndex(
            model_name="topiccrossreference",
            index=models.Index(fields=["relevance_score"], name="topic_cross_relevan_0b77c5_idx"),
        ),
        migrations.AddConstraint(
            model_name="topiccrossreference",
            constraint=models.UniqueConstraint(fields=("topic", "cross_reference"), name="uniq_topic_xref"),
        ),
        migrations.AddIndex(
            model_name="topiccontent",
            index=models.Index(fields=["topic", "language"], name="topiccontent_topic_lang_idx"),
        ),
        migrations.AddConstraint(
            model_name="topiccontent",
            constraint=models.UniqueConstraint(fields=("topic", "language"), name="uniq_topic_content_per_language"),
        ),
        migrations.AddConstraint(
            model_name="topicaspectlabel",
            constraint=models.UniqueConstraint(fields=("aspect", "language"), name="uniq_aspect_label_per_language"),
        ),
        migrations.AddIndex(
            model_name="topicaspect",
            index=models.Index(fields=["topic", "order"], name="topic_aspec_topic_i_1c1327_idx"),
        ),
        migrations.AddIndex(
            model_name="topicaspect",
            index=models.Index(fields=["slug"], name="topic_aspec_slug_d10b69_idx"),
        ),
    ]
