# Generated by Django 4.2.7 on 2025-12-06 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0021_crossref_and_topics_enriched"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentaryentry",
            name="author",
        ),
        migrations.RemoveField(
            model_name="commentaryentry",
            name="book",
        ),
        migrations.RemoveField(
            model_name="commentaryentry",
            name="source",
        ),
        migrations.RemoveField(
            model_name="commentarysource",
            name="language",
        ),
        migrations.RemoveField(
            model_name="commentarysource",
            name="license",
        ),
        migrations.RemoveField(
            model_name="versecomment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="versecomment",
            name="verse",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="CommentaryEntry",
        ),
        migrations.DeleteModel(
            name="CommentarySource",
        ),
        migrations.DeleteModel(
            name="VerseComment",
        ),
    ]
