# Generated by Django 4.2.7 on 2026-03-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bible", "0022_initial_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chapter", models.PositiveIntegerField()),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=50)),
                ("entities_found", models.PositiveIntegerField(default=0)),
                ("symbols_found", models.PositiveIntegerField(default=0)),
                ("links_created", models.PositiveIntegerField(default=0)),
                ("links_removed", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="bible.canonicalbook",
                    ),
                ),
            ],
            options={
                "db_table": "ai_chapter_analysis",
                "unique_together": {("book", "chapter")},
            },
        ),
    ]
